#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.StudentSchool.Views.Detail.LearningStandardsList
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    
    #line 1 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
    using System.Web.Script.Serialization;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line 2 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Areas.StudentSchool.Models.Detail.LearningStandardsList;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Architecture;
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    #line 3 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
    using IronRuby.Compiler.Ast;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/StudentSchool/Views/Detail/LearningStandardsList/Get.cshtml")]
    public partial class Get : System.Web.Mvc.WebViewPage<Areas.StudentSchool.Models.Detail.LearningStandardsList.LearningStandardsModel>
    {

public System.Web.WebPages.HelperResult RenderLeftRow(int visibleRows, LearningStandardsDataItem item, int generatedId)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 18 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
     
    if (null == item)
    {
        return;
    }
    
    var highlight = (visibleRows % 2 == 1 && item.level <= 0) ? "highlighted" : "";
    var nameColumnId = null != item.name ? item.name.Replace(@"[^a-z0-9]", "") : string.Empty;
    

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <tr class=\"level-");



#line 27 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
WriteTo(@__razor_helper_writer, item.level);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " ");



#line 27 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
      WriteTo(@__razor_helper_writer, highlight);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-tag=\"");



#line 27 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                            WriteTo(@__razor_helper_writer, item.tag);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-linktoheaders=\"");



#line 27 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                            WriteTo(@__razor_helper_writer, item.linkToHeaders ?? "");

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n            <th id=\"LearningStandardsTable_");



#line 28 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
             WriteTo(@__razor_helper_writer, generatedId);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "_");



#line 28 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                            WriteTo(@__razor_helper_writer, nameColumnId);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 29 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                 if (item.children != null && item.children.Any())
                {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    <a href=\"#\">");



#line 31 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
 WriteTo(@__razor_helper_writer, item.name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 32 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                }
                else
                {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    ");



#line 35 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
WriteTo(@__razor_helper_writer, item.name);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 36 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            </th>\r\n        </tr>\r\n");



#line 39 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"

    if (item.children != null)
    {
        for (var i = 0; i < item.children.Count(); i++)
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            ");

WriteLiteralTo(@__razor_helper_writer, "\r\n                ");



#line 45 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
WriteTo(@__razor_helper_writer, RenderLeftRow(visibleRows, item.children.ElementAt(i), generatedId));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n            ");

WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 47 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
        }
    }

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult RenderRightRow(int visibleRows, LearningStandardsDataItem item, int generatedId)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 52 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
     
    if (null == item)
    {
        return;
    }

    var highlight = (visibleRows % 2 == 1 && item.level <= 0) ? "highlighted" : "";
    var nameColumnId = null != item.name ? item.name.Replace(@"[^a-z0-9]", "") : string.Empty;
    

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        <tr class=\"level-");



#line 61 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
WriteTo(@__razor_helper_writer, item.level);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " ");



#line 61 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
      WriteTo(@__razor_helper_writer, highlight);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-tag=\"");



#line 61 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                            WriteTo(@__razor_helper_writer, item.tag);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" data-linktoheaders=\"");



#line 61 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                            WriteTo(@__razor_helper_writer, item.linkToHeaders ?? "");

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 62 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
             foreach (var col in Model.schema)
            {
                var displayValue = string.Empty;
                LearningStandardsDataItemValue dataItem;

                if (item.values != null && item.values.Any() && item.values.TryGetValue(col.Key, out dataItem))
                {
                    displayValue = dataItem.displayValue;
                    if (dataItem.type == "template")
                    {
                        var className = "";
                        switch (dataItem.displayValue)
                        {
                            case "high":
                                className = "RoundVeryGood";
                                break;
                            case "med":
                                className = "RoundGood";
                                break;
                            case "low":
                                className = "RoundLow";
                                break;
                            case "none":
                                className = "RoundNone";
                                break;
                        }

                        displayValue = string.Format("<div class=\"{0}\"></div>", className);
                    }
                }

                if (!String.IsNullOrWhiteSpace(displayValue))
                {


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    <td data-tag=\"");



#line 96 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
   WriteTo(@__razor_helper_writer, col.Key);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" aria-labeledby=\"LearningStandardsTable_");



#line 96 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                     WriteTo(@__razor_helper_writer, generatedId);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "_");



#line 96 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                                    WriteTo(@__razor_helper_writer, nameColumnId);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 96 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                                                    WriteTo(@__razor_helper_writer, Html.Raw(displayValue));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</td>\r\n");



#line 97 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                }
                else
                {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    <td data-tag=\"");



#line 100 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
   WriteTo(@__razor_helper_writer, col.Key);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" aria-labeledby=\"LearningStandardsTable_");



#line 100 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                     WriteTo(@__razor_helper_writer, generatedId);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "_");



#line 100 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                                    WriteTo(@__razor_helper_writer, nameColumnId);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"></td>\r\n");



#line 101 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                }
            }

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "        </tr>\r\n");



#line 104 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"

    if (item.children != null)
    {
        for (var i = 0; i < item.children.Count(); i++)
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                ");

WriteLiteralTo(@__razor_helper_writer, "\r\n                    ");



#line 110 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
WriteTo(@__razor_helper_writer, RenderRightRow(visibleRows, item.children.ElementAt(i), generatedId));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n                ");

WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 112 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
        }
    }

#line default
#line hidden

});

}


        public Get()
        {
        }
        public override void Execute()
        {





            
            #line 5 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
  
    // TODO: should replace this with a better uniqueness generator for the id
    var generatedId = (new Random(BitConverter.ToInt32(Guid.NewGuid().ToByteArray(), 0))).Next();



            
            #line default
            #line hidden
WriteLiteral("<!-- TODO: Relocate after UI refactor. -->\r\n");


            
            #line 11 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
 if (Model.data == null)
{

            
            #line default
            #line hidden
WriteLiteral("                <span class=\"MetricNoData\">No data available.</span>\r\n");


            
            #line 14 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
}
else
{

            
            #line default
            #line hidden

            
            #line 49 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
 


            
            #line default
            #line hidden

            
            #line 114 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
 


            
            #line default
            #line hidden
WriteLiteral("<!--<div class=\"temp-style-header\">(Left)</div>\r\n    <div class=\"temp-style-conte" +
"nt\">-->\r\n");



WriteLiteral("<div id=\"LearningStandardsTable_");


            
            #line 118 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                            Write(generatedId);

            
            #line default
            #line hidden
WriteLiteral(@""" class=""learning-standard"">
    <div class=""maximize-button"">
        <a href=""#"">
            <span class=""maximize"">Maximize View</span>
            <span class=""restore"">Restore View</span>
        </a>    

    </div>
    <div class=""learning-standards-table"">
        <div class=""leftPaneHeaders"">
            <table class=""leftPane-headers"">
                <thead><tr><th class=""group-0"">Learning Standards</th></tr></thead>
            </table>
        </div>
        <div class=""rightPaneHeaders"">
            <table class=""rightPane-headers"">
                <thead>
                    <tr>
");


            
            #line 136 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                         foreach (var column in Model.schema)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <th class=\"group-1\" data-tag=\"");


            
            #line 138 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                     Write(column.Key);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 138 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                                  Write(column.Value);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");


            
            #line 139 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tr>\r\n                </thead>\r\n            </table>\r\n      " +
"  </div>\r\n        <div class=\"leftPane\">\r\n            <div class=\"scroller\">\r\n  " +
"              <table class=\"leftPane-content\">\r\n                    <tbody>\r\n");


            
            #line 148 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                          
                            for (int i = 1; i < Model.data.Count(); i++)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                ");

WriteLiteral("\r\n                                    ");


            
            #line 152 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                               Write(RenderLeftRow(i, Model.data.ElementAt(i), generatedId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                ");

WriteLiteral("\r\n");


            
            #line 154 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                            }
                        

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n            </div>\r\n     " +
"   </div>\r\n        <div class=\"rightPane\">\r\n            <table class=\"rightPane-" +
"content\">\r\n                <tbody>\r\n");


            
            #line 163 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                      
                        for (int i = 1; i < Model.data.Count(); i++)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral("\r\n                                ");


            
            #line 167 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                           Write(RenderRightRow(i, Model.data.ElementAt(i), generatedId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            ");

WriteLiteral("\r\n");


            
            #line 169 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                        }
                    

            
            #line default
            #line hidden
WriteLiteral(@"                </tbody>
            </table>
        </div>
    </div>
    <div class=""learning-standards-legend"">
        <table class=""EdFiGrid-legend"">
            <tr>
                <td style=""width: 100%"">
                    <table id=""EdFiGrid-legend-table_");


            
            #line 179 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                 Write(generatedId);

            
            #line default
            #line hidden
WriteLiteral(@""" class=""EdFiGrid-legend-table"" cellpadding=""0px"" style=""background-color: #E0DFDF;"" cellspacing=""0px"" border=""0px"">
                        <tbody>
                            <tr>
                                <td class=""EdFiGrid-legend-table-image"">
                                    <img src=""");


            
            #line 183 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                         Write(EdFiWebFormsDashboards.Site.Common.ThemeImage("StatusLabel/RoundVeryGood.png").Resolve());

            
            #line default
            #line hidden
WriteLiteral(@""" alt=""Star"" />
                                </td><td class=""EdFiGrid-legend-table-text"">
                                         Advanced
                                     </td><td class=""EdFiGrid-legend-table-image"">
                                              <img src=""");


            
            #line 187 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                   Write(EdFiWebFormsDashboards.Site.Common.ThemeImage("StatusLabel/RoundGood.png").Resolve());

            
            #line default
            #line hidden
WriteLiteral(@""" alt=""Green"" />
                                          </td><td class=""EdFiGrid-legend-table-text"">
                                                   Met Standard
                                               </td><td class=""EdFiGrid-legend-table-image"">
                                                        <img src=""");


            
            #line 191 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                             Write(EdFiWebFormsDashboards.Site.Common.ThemeImage("StatusLabel/RoundLow.png").Resolve());

            
            #line default
            #line hidden
WriteLiteral(@""" alt=""Red"" />
                                                    </td><td class=""EdFiGrid-legend-table-text"">
                                                             Not Mastered
                                                         </td><td class=""EdFiGrid-legend-table-image"">
                                                                  <img src=""");


            
            #line 195 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                                                                       Write(EdFiWebFormsDashboards.Site.Common.ThemeImage("StatusLabel/RoundNone.png").Resolve());

            
            #line default
            #line hidden
WriteLiteral(@""" alt=""Red"" />
                                                              </td><td class=""EdFiGrid-legend-table-text"">
                                                                       Not Tested
                                                                   </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    
    <!-- added style of display: inline-block; for firefox specifically -->

</div>
");


            
            #line 210 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<!--</div>-->\r\n<script type=\"text/javascript\" src=\"");


            
            #line 212 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                               Write(Url.Content("~/Content/Scripts/Application/LearningStandards.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n<script type=\"text/javascript\">\r\n    $(\'#LearningStandardsTable_");


            
            #line 214 "..\..\Areas\StudentSchool\Views\Detail\LearningStandardsList\Get.cshtml"
                           Write(generatedId);

            
            #line default
            #line hidden
WriteLiteral("\').learningStandards();\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
