#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.School.Views.StudentGradeList
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
    using EdFi.Dashboards.Common;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
    using EdFi.Dashboards.Common.Utilities;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
    using EdFi.Dashboards.Core.Providers.Context;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line 5 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Areas.School.Controllers;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Areas.School.Models.StudentGradeList;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Models.Shared;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Providers.Models;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    #line 8 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
    using EdFi.Dashboards.Resources.Navigation.Mvc;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
    using EdFi.Dashboards.SecurityTokenService.Authentication;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/School/Views/StudentGradeList/Get.cshtml")]
    public partial class Get : System.Web.Mvc.WebViewPage<StudentGradeListModel>
    {
        public Get()
        {
        }
        public override void Execute()
        {









WriteLiteral("\r\n");


WriteLiteral("           \r\n");


            
            #line 13 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
  
    //ViewBag.Title = "Grade";
    var safeGradeName = Model.Grade.Replace(" ", "").Replace("/", "").Replace("-", "");
    var localEducationAgencyId = EdFiDashboardContext.Current.LocalEducationAgencyId.GetValueOrDefault();
    var schoolId = EdFiDashboardContext.Current.SchoolId.GetValueOrDefault();
    var staffUSI = UserInformation.Current.StaffUSI;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("ContentPlaceHolderHead", () => {

WriteLiteral("\r\n    <title>");


            
            #line 22 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
       Write(Html.Action("Title", typeof(SchoolLayoutController).GetControllerName(), new { subTitle = Model.Grade }));

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <script type=\"text/javascript\">\r\n        var pageArea = { Area: \'sc" +
"hool\', Page: \'Students by Grade\' };\r\n    </script>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("ContentPlaceHolder1", () => {

WriteLiteral("\r\n    <div class=\"student-drop-down\" id=\"gradeSelector\">\r\n        <h2>Students by" +
" Grade</h2>\r\n        <label class=\"content-label\" for=\"gradeSelect\">Select grade" +
" to show:</label>\r\n        <select id=\"gradeSelect\" class=\"drop-down\">\r\n");


            
            #line 33 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
             foreach (var grade in Model.MenuModel.Grades)
            {

            
            #line default
            #line hidden
WriteLiteral("                <option value=\"");


            
            #line 35 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
                          Write(grade.Url);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n");


            
            #line 36 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
                     if (Request.Url != null && grade.Attribute==Model.Grade)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("selected=\'selected\'\r\n");


            
            #line 39 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
                    }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                    ");


            
            #line 40 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
               Write(grade.Attribute);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </option>\r\n");


            
            #line 42 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </select>\r\n    </div>\r\n<script type=\"text/javascript\">\r\n    $(document).r" +
"eady(function () {\r\n        $(\"#gradeSelect\").navigateOnChange();\r\n        $(\'#G" +
"rade");


            
            #line 48 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
             Write(safeGradeName);

            
            #line default
            #line hidden
WriteLiteral("-EdFiGrid-interaction-custom\').append($(\'#buttonExportAll");


            
            #line 48 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
                                                                                      Write(safeGradeName);

            
            #line default
            #line hidden
WriteLiteral("\'));\r\n        $(\'#buttonExportAll");


            
            #line 49 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
                       Write(safeGradeName);

            
            #line default
            #line hidden
WriteLiteral("\').show();\r\n        $(\'#Grade");


            
            #line 50 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
             Write(safeGradeName);

            
            #line default
            #line hidden
WriteLiteral("-EdFiGrid\').bind(\'afterDrawEvent\', function(e, table) {\r\n                        " +
"Grade");


            
            #line 51 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
                         Write(safeGradeName);

            
            #line default
            #line hidden
WriteLiteral("CustomStudentList.redrawCheckboxes();\r\n                    });\r\n    });\r\n</script" +
">\r\n    \r\n\r\n");


            
            #line 57 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
      
        if (Model.GridData != null)
        {
            var callbackUrl = EdFiDashboardContext.Current.RoutedUrl;

            var edFiGridModelProvider = IoC.Resolve<IEdFiGridModelProvider>();
           
            var edfiGridModel = edFiGridModelProvider.GetEdFiGridModel(
                displayInteractionMenu: true, 
                displayAddRemoveColumns: true, 
                fixedHeight: 0, 
                name: "Grade" + safeGradeName, 
                metricVariantId: null, 
                gridTable: Model.GridData, 
                metricFootnotes: null, 
                nonPersistedSettings: null, 
                sizeToWindow: true, 
                listType: "StudentList", 
                legendViewNames: new List<string> { "Default" }, 
                hrefToUse: null, 
                usePagination: true, 
                paginationCallbackUrl: callbackUrl, 
                allowMaximizeGrid: true, 
                studentWatchlist: null, 
                selectedDemographicOption: null, 
                selectedSchoolCategoryOption: null, 
                selectedGradeOption: Model.Grade, 
                previousNextSessionPage: Model.PreviousNextSessionPage, 
                exportGridDataUrl: Model.ExportGridDataUrl, 
                gridListType: Model.ListType);
        
            var customStudentListModel = new CustomStudentListModel
            {
                ControlId = "Grade" + safeGradeName,
                IsCustomStudentList = false,
                LinkParentIdentifier = "#Grade" + safeGradeName + "-EdFiGrid-interaction-custom",
                CheckboxParentIentifier = "#Grade" + safeGradeName + "-EdFiGrid-fixed-data-table",
                SelectAllCheckboxParentIentifier = "#Grade" + safeGradeName + "-EdFiGrid-fixed-header-table",
                CustomStudentListId = null,
                LocalEducationAgencyId = localEducationAgencyId,
                SchoolId = schoolId,
                StaffUSI = staffUSI,
                CustomStudentListUrl = EdFiDashboards.Site.Staff.CustomStudentList(schoolId, staffUSI, null, new { format = "json" }),
                UniqueId = schoolId
            };


            
            #line default
            #line hidden
WriteLiteral("            <a href=\"#\" id=\"buttonExportAll");


            
            #line 103 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
                                       Write(safeGradeName);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn\" style=\"display:none;\" onclick=\"Grade");


            
            #line 103 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
                                                                                                         Write(safeGradeName);

            
            #line default
            #line hidden
WriteLiteral("EdFiGrid.exportGrid();\"><i class=\"icon-floppy\"></i> EXPORT ALL</a>\r\n");


            
            #line 104 "..\..\Areas\School\Views\StudentGradeList\Get.cshtml"
            Html.RenderPartial("EdFiGrid", edfiGridModel);
            Html.RenderPartial("CustomStudentList", customStudentListModel);
        }
    

            
            #line default
            #line hidden

});


        }
    }
}
#pragma warning restore 1591
