#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.StudentSchool.Views.Detail.HistoricalLearningObjectivesChart
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    
    #line 1 "..\..\Areas\StudentSchool\Views\Detail\HistoricalLearningObjectivesChart\Get.cshtml"
    using System.Web.UI.DataVisualization.Charting;
    
    #line default
    #line hidden
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\StudentSchool\Views\Detail\HistoricalLearningObjectivesChart\Get.cshtml"
    using EdFi.Dashboards.Core.Providers.Context;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    
    #line 3 "..\..\Areas\StudentSchool\Views\Detail\HistoricalLearningObjectivesChart\Get.cshtml"
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Architecture;
    
    #line 4 "..\..\Areas\StudentSchool\Views\Detail\HistoricalLearningObjectivesChart\Get.cshtml"
    using EdFi.Dashboards.Presentation.Web.Architecture.HtmlHelperExtensions;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/StudentSchool/Views/Detail/HistoricalLearningObjectivesChart/Get.cshtml")]
    public class Get : System.Web.Mvc.WebViewPage<EdFi.Dashboards.Presentation.Core.Models.Shared.Detail.ChartViewModel>
    {
        public Get()
        {
        }
        public override void Execute()
        {





WriteLiteral("\n");


            
            #line 7 "..\..\Areas\StudentSchool\Views\Detail\HistoricalLearningObjectivesChart\Get.cshtml"
  
  var studentUSI = EdFiDashboardContext.Current.StudentUSI.GetValueOrDefault();
  var metricVariantId = EdFiDashboardContext.Current.MetricVariantId.GetValueOrDefault();


            
            #line default
            #line hidden
WriteLiteral("\n    <script>\r\n        analyticsManager.trackDrilldown(\'StudentHistoricalLearning" +
"ObjectivesChart\', \'");


            
            #line 13 "..\..\Areas\StudentSchool\Views\Detail\HistoricalLearningObjectivesChart\Get.cshtml"
                                                                                 Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\', \'");


            
            #line 13 "..\..\Areas\StudentSchool\Views\Detail\HistoricalLearningObjectivesChart\Get.cshtml"
                                                                                                       Write(studentUSI);

            
            #line default
            #line hidden
WriteLiteral("\');\n    </script>\n    <div>\r\n");


            
            #line 16 "..\..\Areas\StudentSchool\Views\Detail\HistoricalLearningObjectivesChart\Get.cshtml"
         if(Model != null && Model.ChartData != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <p class=\"chart-goal\">");


            
            #line 18 "..\..\Areas\StudentSchool\Views\Detail\HistoricalLearningObjectivesChart\Get.cshtml"
                             Write(Model.ChartData.Goal);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 19 "..\..\Areas\StudentSchool\Views\Detail\HistoricalLearningObjectivesChart\Get.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");


            
            #line 20 "..\..\Areas\StudentSchool\Views\Detail\HistoricalLearningObjectivesChart\Get.cshtml"
   Write(Html.BarChart(Model));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n");


        }
    }
}
#pragma warning restore 1591
