#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.StudentSchool.Views.Detail.ClassAbsencesChart
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
    using EdFi.Dashboards.Core.Providers.Context;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line 2 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Areas.StudentSchool.Controllers.Detail;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Architecture;
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/StudentSchool/Views/Detail/ClassAbsencesChart/Get.cshtml")]
    public partial class Get : System.Web.Mvc.WebViewPage<EdFi.Dashboards.Resources.Models.Student.Detail.ClassAbsencesModel>
    {
        public Get()
        {
        }
        public override void Execute()
        {



WriteLiteral("\n");


            
            #line 5 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
  
    var studentUSI = EdFiDashboardContext.Current.StudentUSI.GetValueOrDefault();
    var metricVariantId = EdFiDashboardContext.Current.MetricVariantId.GetValueOrDefault();

    int weeksPerRow = 4;
    int weekCount = 0;

    if (Model != null && Model.Classes.Any())
    {
        weekCount = Model.Classes.First().Weeks.Count();
        // this helps balance the distribution of weeks better
        //  we don't want this             instead do this
        //    W W W W                          W W W
        //    W W                              W W W
        if (weekCount == 5 || weekCount == 6 || weekCount == 9)
        {
            weeksPerRow = 3;
        }
    }
    int rowCount = Convert.ToInt32(Math.Ceiling(weekCount / Convert.ToDouble(weeksPerRow)));


            
            #line default
            #line hidden
WriteLiteral("<script>\r\n    analyticsManager.trackDrilldown(\'StudentClassAbsencesChart\', \'");


            
            #line 27 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                              Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\', \'");


            
            #line 27 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                    Write(studentUSI);

            
            #line default
            #line hidden
WriteLiteral("\');\n</script>\n\r\n");


            
            #line 30 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
 if (Model != null && Model.Classes.Any())
{ 


            
            #line default
            #line hidden
WriteLiteral("    <style>\r\n        \r\n\r\n    </style>\r\n");


            
            #line 37 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <table class=\"class-absences-chart\" id=\"class-absences-chart-");


            
            #line 38 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                             Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\" summary=\"This table displays the attendance record of a student for all classes" +
"\">\r\n        <tfoot>\r\n            <tr>\n                <th id=\"icon-meanings");


            
            #line 41 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                 Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\"></th>\r\n                <td headers=\"icon-meanings");


            
            #line 42 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                      Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral(@""" colspan=""20"">
                    <span class=""attendance""><span class=""attendance-footer-box attendance-type attendance-type-Present""></span></span>
                    <span class=""attendance"">In Attendance</span>
                    <span class=""attendance""></span>
                    <span class=""attendance""><span style=""position: relative; top: -5px;"" class=""attendance-footer-box attendance-type attendance-type-Unexcused""></span></span>
                    <span class=""attendance"">Unexcused Absence</span>
                    <span class=""attendance""></span>
                    <span class=""attendance""><span class=""attendance-footer-box attendance-type attendance-type-Excused""></span></span>
                    <span class=""attendance"">Excused</span>
                    <span class=""attendance""></span>
                    <span class=""attendance""><span style=""position: relative; top: -5px;"" class=""attendance-footer-box attendance-type attendance-type-Tardy""></span></span>
                    <span class=""attendance"">Tardy</span>
                    <span class=""attendance""></span>
                </td>
            </tr>
            <tr>
                <th id=""footerDisclaimer");


            
            #line 58 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                    Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\"></th>\r\n                <td headers=\"footerDisclaimer");


            
            #line 59 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                         Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral(@""" colspan=""20"">
                    <ul>
                        <li>Does not account for missing roll occurrences</li>
                        <li>Not all courses meet daily</li>
                    </ul>
                </td>
            </tr>
        </tfoot>
        <tbody>
");


            
            #line 68 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
             for (var i = 0; i < rowCount; i++){
                int currentRow = i;

                var classes = Model.Classes.First().Weeks.Skip(currentRow * weeksPerRow).Take(weeksPerRow);


            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <th id=\"emptyCell");


            
            #line 74 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                 Write(i);

            
            #line default
            #line hidden

            
            #line 74 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                     Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\"></th>\r\n");


            
            #line 75 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                     foreach (var theClass in classes)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <th colspan=\"5\" id=\"week");


            
            #line 77 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                            Write(theClass.StartDate);

            
            #line default
            #line hidden
WriteLiteral("-");


            
            #line 77 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                  Write(theClass.EndDate);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 77 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                       Write(theClass.StartDate.ToString("MM/dd"));

            
            #line default
            #line hidden
WriteLiteral(" - ");


            
            #line 77 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                                                                 Write(theClass.EndDate.ToString("MM/dd"));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");


            
            #line 78 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");



WriteLiteral("                <tr class=\"day-headers\">\r\n                    <th id=\"otherEmptyC" +
"ell");


            
            #line 81 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                      Write(i);

            
            #line default
            #line hidden

            
            #line 81 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                          Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\"></th>\r\n");


            
            #line 82 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                     foreach (var theClass2 in classes)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <th class=\"day-header day-header-monday\" id=\"Monday");


            
            #line 84 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                       Write(theClass2.StartDate.ToString("MM-dd-yy"));

            
            #line default
            #line hidden
WriteLiteral("_");


            
            #line 84 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                                                   Write(theClass2.EndDate.ToString("MM-dd-yy"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <span class=\"hidden\">Monday</span>\r\n             " +
"           </th>\r\n");



WriteLiteral("                        <th class=\"day-header day-header-tuesday\" id=\"Tuesday");


            
            #line 87 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                         Write(theClass2.StartDate.ToString("MM-dd-yy"));

            
            #line default
            #line hidden
WriteLiteral("_");


            
            #line 87 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                                                     Write(theClass2.EndDate.ToString("MM-dd-yy"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <span class=\"hidden\">Tuesday</span>\r\n            " +
"            </th>\r\n");



WriteLiteral("                        <th class=\"day-header day-header-wednesday\" id=\"Wednesday" +
"");


            
            #line 90 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                             Write(theClass2.StartDate.ToString("MM-dd-yy"));

            
            #line default
            #line hidden
WriteLiteral("_");


            
            #line 90 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                                                         Write(theClass2.EndDate.ToString("MM-dd-yy"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <span class=\"hidden\">Wednesday</span>\r\n          " +
"              </th>\r\n");



WriteLiteral("                        <th class=\"day-header day-header-thursday\" id=\"Thursday");


            
            #line 93 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                           Write(theClass2.StartDate.ToString("MM-dd-yy"));

            
            #line default
            #line hidden
WriteLiteral("_");


            
            #line 93 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                                                       Write(theClass2.EndDate.ToString("MM-dd-yy"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <span class=\"hidden\">Thursday</span>\r\n           " +
"             </th>\r\n");



WriteLiteral("                        <th class=\"day-header day-header-friday\" id=\"Friday");


            
            #line 96 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                       Write(theClass2.StartDate.ToString("MM-dd-yy"));

            
            #line default
            #line hidden
WriteLiteral("_");


            
            #line 96 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                                                   Write(theClass2.EndDate.ToString("MM-dd-yy"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <span class=\"hidden\">Friday</span>\r\n             " +
"           </th>\r\n");


            
            #line 99 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");


            
            #line 101 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                foreach(var theClass3 in Model.Classes){

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <th class=\"class-label\" id=\"abs" +
"ence-metric");


            
            #line 103 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                              Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("-class-");


            
            #line 103 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                       Write(theClass3.Name.Replace(" ", "-"));

            
            #line default
            #line hidden

            
            #line 103 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                                                          Write(i);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 103 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                                                                Write(theClass3.Name);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");


            
            #line 104 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                         foreach (var week in theClass3.Weeks.Skip(currentRow * weeksPerRow).Take(weeksPerRow))
                        {
                            foreach (var theEvent in week.WeekDayEvents)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <td class=\"attendance\" headers=\"absence-metric");


            
            #line 108 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                          Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("-class-");


            
            #line 108 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                                   Write(theClass3.Name.Replace(" ", "-"));

            
            #line default
            #line hidden

            
            #line 108 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                                                                      Write(i);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 108 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                                                                                                   Write(ClassAbsencesChartController.GetDayTooltip(theEvent.AttendanceEventType, theEvent.Date, theEvent.Reason));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                    <div class=\"attendance-type attendance-ty" +
"pe-");


            
            #line 109 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                                            Write(theEvent.AttendanceEventType);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                        <span class=\"hidden\">");


            
            #line 110 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                                                         Write(ClassAbsencesChartController.GetDayText(theEvent.AttendanceEventType));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                    </div>\r\n                            " +
"    </td>\r\n");


            
            #line 113 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                            }
                        } 

            
            #line default
            #line hidden
WriteLiteral("                    </tr>\r\n");


            
            #line 116 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");


            
            #line 120 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div class=\"metric-footnote-tooltip\" id=\"divToolTipForCalendar\"></div>\r\n");



WriteLiteral(@"    <script>
      $(document).ready(function () {
        $('td[title]').not('[title=""""]').tooltip({
          tip: '#divToolTipForCalendar',
          effect: 'fade',
          position: 'bottom center',
          bounce: true,
          offset: [0, 0],
          delay: 0
        });
      });
    </script> 
");


            
            #line 134 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <p class=\"metric-no-data\">No data available.</p>\r\n");


            
            #line 138 "..\..\Areas\StudentSchool\Views\Detail\ClassAbsencesChart\Get.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
