#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.StudentSchool.Views.Detail.StateAssessmentNormalizedChart
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    
    #line 1 "..\..\Areas\StudentSchool\Views\Detail\StateAssessmentNormalizedChart\Get.cshtml"
    using System.Web.UI.DataVisualization.Charting;
    
    #line default
    #line hidden
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\StudentSchool\Views\Detail\StateAssessmentNormalizedChart\Get.cshtml"
    using EdFi.Dashboards.Core.Providers.Context;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    using EdFi.Dashboards.Presentation.Web.Architecture;
    
    #line 3 "..\..\Areas\StudentSchool\Views\Detail\StateAssessmentNormalizedChart\Get.cshtml"
    using EdFi.Dashboards.Presentation.Web.Architecture.HtmlHelperExtensions;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/StudentSchool/Views/Detail/StateAssessmentNormalizedChart/Get.cshtml")]
    public class Get : System.Web.Mvc.WebViewPage<EdFi.Dashboards.Resources.Models.Charting.ChartData>
    {
        public Get()
        {
        }
        public override void Execute()
        {




WriteLiteral("\r\n");


            
            #line 6 "..\..\Areas\StudentSchool\Views\Detail\StateAssessmentNormalizedChart\Get.cshtml"
  
  var studentUSI = EdFiDashboardContext.Current.StudentUSI.GetValueOrDefault();
  var metricVariantId = EdFiDashboardContext.Current.MetricVariantId.GetValueOrDefault();


            
            #line default
            #line hidden
WriteLiteral("\r\n<script type=\"text/javascript\" language=\"javascript\">\r\n    analyticsManager.tra" +
"ckDrilldown(\'StudentStateAssessmentNormalizedChart\', \'");


            
            #line 12 "..\..\Areas\StudentSchool\Views\Detail\StateAssessmentNormalizedChart\Get.cshtml"
                                                                          Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\', \'");


            
            #line 12 "..\..\Areas\StudentSchool\Views\Detail\StateAssessmentNormalizedChart\Get.cshtml"
                                                                                                Write(studentUSI);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n</script>\r\n");


            
            #line 14 "..\..\Areas\StudentSchool\Views\Detail\StateAssessmentNormalizedChart\Get.cshtml"
 if (Model == null)
{

            
            #line default
            #line hidden
WriteLiteral("    <span class=\"MetricNoData\">No data available.</span>\r\n");


            
            #line 17 "..\..\Areas\StudentSchool\Views\Detail\StateAssessmentNormalizedChart\Get.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        ");


            
            #line 21 "..\..\Areas\StudentSchool\Views\Detail\StateAssessmentNormalizedChart\Get.cshtml"
   Write(Html.BarChart(Model, 740, 250, 110, 0, 110, "{0}", false, SeriesChartType.Column, true));

            
            #line default
            #line hidden
WriteLiteral(@"

        <span class=""MetricSubTitle"">Scores include both scale and vertical scores which are not comparable. Graph has been normalized to show scores relative to Met Standard and Commended levels.</span><br />
        <span class=""MetricSubTitle"">*Bar graphs missing due to historical raw score data missing for students transferring into district.</span>
    </div>
");


            
            #line 26 "..\..\Areas\StudentSchool\Views\Detail\StateAssessmentNormalizedChart\Get.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
