#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    
    #line 2 "..\..\Areas\School\Views\Information\Get.cshtml"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\School\Views\Information\Get.cshtml"
    using EdFi.Dashboards.Common;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\School\Views\Information\Get.cshtml"
    using EdFi.Dashboards.Core;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\School\Views\Information\Get.cshtml"
    using EdFi.Dashboards.Core.Providers.Context;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line 6 "..\..\Areas\School\Views\Information\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Areas.School.Controllers;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\School\Views\Information\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Utilities.ExtensionMethods.HtmlHelper;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/School/Views/Information/Get.cshtml")]
    public partial class _Areas_School_Views_Information_Get_cshtml : System.Web.Mvc.WebViewPage<EdFi.Dashboards.Resources.Models.School.Information.InformationModel>
    {
        public _Areas_School_Views_Information_Get_cshtml()
        {
        }
        public override void Execute()
        {







WriteLiteral("\r\n");


            
            #line 9 "..\..\Areas\School\Views\Information\Get.cshtml"
  
    //ViewBag.Title = "School Information";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("ContentPlaceHolderHead", () => {

WriteLiteral("\r\n    <title>");


            
            #line 14 "..\..\Areas\School\Views\Information\Get.cshtml"
       Write(Html.Action("Title", typeof(SchoolLayoutController).GetControllerName(), new { subTitle = "School Information" }));

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <script type=\"text/javascript\">\r\n        var pageArea = { Area: \'sc" +
"hool\', Page: \'School Information\' };\r\n    </script>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("ContentPlaceHolder1", () => {

WriteLiteral("\r\n\r\n");


            
            #line 22 "..\..\Areas\School\Views\Information\Get.cshtml"
      
        var localEducationAgencyId = EdFiDashboardContext.Current.LocalEducationAgencyId.GetValueOrDefault();
        var schoolId = EdFiDashboardContext.Current.SchoolId.GetValueOrDefault();
    

            
            #line default
            #line hidden
WriteLiteral(@"
    <div class=""tab-content"">
        <div role=""tabpanel"" class=""tab-pane active tab-red-damask"" id=""tab-student-info"">
            <div class=""action-btn action-btn-red-damask"">
                <a class=""btn"" href=""#""><i class=""fa fa-download""></i></a>
                <a class=""btn"" href=""#""><i class=""fa fa-print""></i></a>
                <a class=""btn"" href=""#""><i class=""fa fa-pencil""></i></a>
            </div>
            <div class=""clearfix edfitable clear"">
                <div class=""col-sm-6 col-md-4 std-grid-md-4"">
                    <div class=""std-primary-col first"">
                        <div class=""row pt40 mb20"">
                            <h3 class=""std-name std-red-damask schoolhead"">");


            
            #line 38 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                                       Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(@"</h3>
                            <div class=""col-xs-6 sm-pr0 std-primary-xs-small"">
                                <div class=""std-info relative"">
                                    <div class=""left"">
                                        <!-- std-thumbnail -->
                                        ");



WriteLiteral("\r\n                                        <img id=\"StudentInformation.ProfileThum" +
"bnail\" src=\"");


            
            #line 44 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                                                       Write(Model.ProfileThumbnail);

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Photograph of ");


            
            #line 44 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                                                                                                     Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(@""" />
                                    </div>
                                </div>
                            </div>
                            <div class=""col-xs-6 sm-pl0 sm-pr0 std-primary-xs-small"">
                                <address class=""std-address"">
");


            
            #line 50 "..\..\Areas\School\Views\Information\Get.cshtml"
                                     foreach (var addressLine in Model.AddressLines)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 52 "..\..\Areas\School\Views\Information\Get.cshtml"
                                    Write(addressLine);

            
            #line default
            #line hidden

WriteLiteral("<br />\r\n");


            
            #line 53 "..\..\Areas\School\Views\Information\Get.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <span id=\"StudentInformation.CityStateZipCode" +
"\">");


            
            #line 54 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                                               Write(Model.ZipCode);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                </address>\r\n                            " +
"    <div class=\"std-desc\">\r\n");


            
            #line 57 "..\..\Areas\School\Views\Information\Get.cshtml"
                                     foreach (var telephoneNumber in Model.TelephoneNumbers)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <span class=\"tel\"><i class=\"icon icon-tel" +
"\"></i>");


            
            #line 59 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                                                   Write(telephoneNumber.Number);

            
            #line default
            #line hidden
WriteLiteral("</span>");



WriteLiteral("<span>&nbsp;&nbsp;");


            
            #line 59 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                                                                                                     Write(telephoneNumber.Type);

            
            #line default
            #line hidden
WriteLiteral("</span>");



WriteLiteral("<br />\r\n");


            
            #line 60 "..\..\Areas\School\Views\Information\Get.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    ");



WriteLiteral(@"
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=""col-sm-6 col-md-4 std-grid-md-5"">
                    <div class=""std-primary-col std-primary-col-second"">
                        <div class=""sm-pl3 clearfix"">
                            <h4 class=""std-title-red-damask"">Administration</h4>
");


            
            #line 71 "..\..\Areas\School\Views\Information\Get.cshtml"
                             foreach (var administrator in Model.Administration)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div class=\"split\">\r\n                            " +
"        <h5 class=\"std-sub-title\">");


            
            #line 74 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                         Write(administrator.Role);

            
            #line default
            #line hidden
WriteLiteral(" : </h5><span> ");


            
            #line 74 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                                                           Write(administrator.Name);

            
            #line default
            #line hidden
WriteLiteral(" </span>\r\n                                </div>\r\n");


            
            #line 76 "..\..\Areas\School\Views\Information\Get.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                        <div class=\"row\">\r\n      " +
"                      <div class=\"sm-pl30 sm-p130new\">\r\n                        " +
"        <h4 class=\"std-title-red-damask\">Accountability</h4>\r\n");


            
            #line 81 "..\..\Areas\School\Views\Information\Get.cshtml"
                                 foreach (var accountability in Model.Accountability)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <h5 class=\"std-sub-title\">");


            
            #line 83 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                         Write(accountability.Attribute);

            
            #line default
            #line hidden
WriteLiteral(" : </h5> ");


            
            #line 83 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                                                                
            
            #line default
            #line hidden
            
            #line 83 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                                                           Write(accountability.Value);

            
            #line default
            #line hidden

WriteLiteral(" <br />\r\n");


            
            #line 84 "..\..\Areas\School\Views\Information\Get.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral(@"                            </div>
                        </div>
                    </div>
                </div>
                <div class=""clearfix visible-sm""></div>
                <div class=""col-sm-12 col-md-4 std-grid-md-3"">
                    <div class=""std-primary-col std-primary-col-third"">
                        <div class=""sm-pl20"">
                            <h4 class=""std-title-red-damask"">School Population</h4>
                            <table class=""table table-demograhpics"">
                                <span class=""label labelheadd""> ");


            
            #line 95 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                            Write(Html.AttributeItemNumberWithUrl(Model.GradePopulation.TotalNumberOfStudents));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 96 "..\..\Areas\School\Views\Information\Get.cshtml"
                                 foreach (var gradePopulation in Model.GradePopulation.TotalNumberOfStudentsByGrade)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <tr>\r\n                                       " +
" <td>\r\n                                            ");


            
            #line 100 "..\..\Areas\School\Views\Information\Get.cshtml"
                                        Write(Html.AttributeItemNumberWithUrl(gradePopulation, false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </td>\r\n                                " +
"    </tr>\r\n");


            
            #line 103 "..\..\Areas\School\Views\Information\Get.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </table>\r\n                            <hr />\r\n       " +
"                     <div class=\"labelheaddtot\">");


            
            #line 106 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                   Write(Html.AttributeItemPercentageWithUrl(Model.GradePopulation.SchoolLateEnrollment));

            
            #line default
            #line hidden
WriteLiteral(@"</div>
                            <hr />
                        </div>
                        <div class=""sm-pl20"">
                            <h4 class=""std-title-red-damask"">High School Graduation Plan</h4>
                            <table class=""table table-demograhpics"">
");


            
            #line 112 "..\..\Areas\School\Views\Information\Get.cshtml"
                                 foreach (var graduationPlan in Model.HighSchoolGraduationPlan)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <tr>\r\n                                       " +
" <td>\r\n                                            ");


            
            #line 116 "..\..\Areas\School\Views\Information\Get.cshtml"
                                        Write(Html.AttributeItemPercentageWithUrl(graduationPlan));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </td>\r\n                                " +
"    </tr>\r\n");


            
            #line 119 "..\..\Areas\School\Views\Information\Get.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral(@"                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""row std-secondarymain"">
            <div class=""std-secondary no-gutter clearfix"">
                <div class=""col-sm-6 col-md-4 std-tablefirst"">
                    <h4 class=""std-secondary-title first"">Student Demographics</h4>
                    <div class=""std-secondary-col first"">
                        <table class=""table std-table"">
                            <tr>
                                <td><b>Gender</b></td>
                                <td>");


            
            #line 134 "..\..\Areas\School\Views\Information\Get.cshtml"
                                Write(Html.AttributeItemPercentageWithUrl(Model.StudentDemographics.Female));

            
            #line default
            #line hidden
WriteLiteral(" <br /> ");


            
            #line 134 "..\..\Areas\School\Views\Information\Get.cshtml"
                                                                                                                Write(Html.AttributeItemPercentageWithUrl(Model.StudentDemographics.Male));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            </tr>\r\n                            <tr>\r\n     " +
"                           <td><b>Ethnicity</b></td>\r\n                          " +
"      <td>\r\n");


            
            #line 139 "..\..\Areas\School\Views\Information\Get.cshtml"
                                     foreach (var ethnicity in Model.StudentDemographics.ByEthnicity)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 141 "..\..\Areas\School\Views\Information\Get.cshtml"
                                    Write(Html.AttributeItemPercentageWithUrl(ethnicity));

            
            #line default
            #line hidden

WriteLiteral(" <br />\r\n");


            
            #line 142 "..\..\Areas\School\Views\Information\Get.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\r\n                            </tr>\r\n       " +
"                     <tr>\r\n                                <td><b>Race</b></td>\r" +
"\n                                <td>\r\n");


            
            #line 148 "..\..\Areas\School\Views\Information\Get.cshtml"
                                     foreach (var ethnicity in Model.StudentDemographics.ByEthnicity)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 150 "..\..\Areas\School\Views\Information\Get.cshtml"
                                    Write(Html.AttributeItemPercentageWithUrl(ethnicity));

            
            #line default
            #line hidden

WriteLiteral(" <br />\r\n");


            
            #line 151 "..\..\Areas\School\Views\Information\Get.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral(@"                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class=""col-sm-6 col-md-4"">
                    <h4 class=""std-secondary-title"">Students by Program</h4>
                    <div class=""std-secondary-col"">
                        <table class=""table std-table"">
");


            
            #line 161 "..\..\Areas\School\Views\Information\Get.cshtml"
                             foreach (var program in Model.StudentsByProgram)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <td>");


            
            #line 164 "..\..\Areas\School\Views\Information\Get.cshtml"
                                    Write(Html.AttributeItemPercentageWithUrl(program));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\r\n                                    ");



WriteLiteral("\r\n                                </tr>\r\n");


            
            #line 175 "..\..\Areas\School\Views\Information\Get.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral(@"                        </table>
                    </div>
                </div>
                <div class=""col-sm-6 col-md-4"">
                    <h4 class=""std-secondary-title"">Other Student Information</h4>
                    <div class=""std-secondary-col"">
                        <table class=""table std-table"">
");


            
            #line 183 "..\..\Areas\School\Views\Information\Get.cshtml"
                             foreach (var indicator in Model.GradePopulation.Indicators)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <td>\r\n " +
"                                       ");


            
            #line 187 "..\..\Areas\School\Views\Information\Get.cshtml"
                                    Write(Html.AttributeItemPercentageWithUrl(indicator));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n");


            
            #line 190 "..\..\Areas\School\Views\Information\Get.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </table>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    ");



WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n}\r\n");


        }
    }
}
#pragma warning restore 1591
