#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Views.MetricTemplates.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MetricTemplates/Shared/BlueHeader.cshtml")]
    public partial class BlueHeader : System.Web.Mvc.WebViewPage<MetricAction>
    {
        public BlueHeader()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\MetricTemplates\Shared\BlueHeader.cshtml"
  
    var dynamicContentName = Legacy.GetDynamicContentNameFromAction(Model);


            
            #line default
            #line hidden
WriteLiteral("\n<div class=\"header-container\">\n<p class=\"header-tab\">");


            
            #line 7 "..\..\Views\MetricTemplates\Shared\BlueHeader.cshtml"
                  Write(Model.DrilldownHeader);

            
            #line default
            #line hidden
WriteLiteral(" <i class=\"icon-right-circled\"></i></p>\n<a id=\"dynamicCloseLink-");


            
            #line 8 "..\..\Views\MetricTemplates\Shared\BlueHeader.cshtml"
                    Write(Model.GetTitleSafeForHtmlId());

            
            #line default
            #line hidden

            
            #line 8 "..\..\Views\MetricTemplates\Shared\BlueHeader.cshtml"
                                                    Write(Model.MetricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"close\" href=\"javascript:ToggleDrillDown(\'#DynamicContentDiv");


            
            #line 8 "..\..\Views\MetricTemplates\Shared\BlueHeader.cshtml"
                                                                                                                                                Write(dynamicContentName);

            
            #line default
            #line hidden
WriteLiteral("\');\"><span class=\"hidden\">Close ");


            
            #line 8 "..\..\Views\MetricTemplates\Shared\BlueHeader.cshtml"
                                                                                                                                                                                                     Write(Model.DrilldownHeader);

            
            #line default
            #line hidden
WriteLiteral("</span><i class=\"icon-cancel\"></i></a>\n</div>\n");


        }
    }
}
#pragma warning restore 1591
