#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Views.MetricTemplates.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line 2 "..\..\Views\MetricTemplates\Shared\StatusLabel.cshtml"
    using EdFi.Dashboards.Presentation.Core.Utilities;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\MetricTemplates\Shared\StatusLabel.cshtml"
    using EdFi.Dashboards.Presentation.Web.Utilities;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MetricTemplates/Shared/StatusLabel.cshtml")]
    public class StatusLabel : System.Web.Mvc.WebViewPage<EdFi.Dashboards.Metric.Resources.Models.State>
    {
        public StatusLabel()
        {
        }
        public override void Execute()
        {



WriteLiteral("<span style=\"");


            
            #line 4 "..\..\Views\MetricTemplates\Shared\StatusLabel.cshtml"
        Write(Legacy.ShowState(Model.StateType));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"");


            
            #line 4 "..\..\Views\MetricTemplates\Shared\StatusLabel.cshtml"
                                                   Write(Legacy.StateClass(Model.StateType));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 4 "..\..\Views\MetricTemplates\Shared\StatusLabel.cshtml"
                                                                                                Write(Model.StateText);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 5 "..\..\Views\MetricTemplates\Shared\StatusLabel.cshtml"
             if (ViewBag.DisplayText != null)
            {
                
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\MetricTemplates\Shared\StatusLabel.cshtml"
           Write(ViewBag.DisplayText);

            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\MetricTemplates\Shared\StatusLabel.cshtml"
                                    
            }
            else
            {
                
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\MetricTemplates\Shared\StatusLabel.cshtml"
           Write(Model.DisplayStateText);

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\MetricTemplates\Shared\StatusLabel.cshtml"
                                       
            }

            
            #line default
            #line hidden
WriteLiteral("            <em class=\"hidden\">");


            
            #line 13 "..\..\Views\MetricTemplates\Shared\StatusLabel.cshtml"
                          Write(Legacy.EvaluateState(Model.StateType));

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n</span>\r\n");


        }
    }
}
#pragma warning restore 1591
