#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.StudentSchool.Views.Detail.LearningObjectivesTable
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
    using EdFi.Dashboards.Common.Utilities;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
    using EdFi.Dashboards.Core.Providers.Context;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line 3 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Providers.Models;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Architecture;
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/StudentSchool/Views/Detail/LearningObjectivesTable/Get.cshtml")]
    public partial class Get : System.Web.Mvc.WebViewPage<EdFi.Dashboards.Resources.Models.CustomGrid.GridTable>
    {
        public Get()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n");


WriteLiteral("\r\n");


            
            #line 7 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
  
    var studentUSI = EdFiDashboardContext.Current.StudentUSI.GetValueOrDefault();
    var metricVariantId = EdFiDashboardContext.Current.MetricVariantId.GetValueOrDefault();
    var edFiGridModelProvider = IoC.Resolve<IEdFiGridModelProvider>();

    var edfiGridModel = edFiGridModelProvider.GetEdFiGridModel(false, true, 10, "Metric" + metricVariantId, metricVariantId,
        Model, null, null, false, null, null, null, false, null, false);



            
            #line default
            #line hidden
WriteLiteral("\r\n<div id=\"LearningStandardsTable");


            
            #line 17 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
                           Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    <script>\r\n        analyticsManager.trackDrilldown(\'StudentLearningObjecti" +
"vesTable\', \'");


            
            #line 19 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
                                                                       Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\', \'");


            
            #line 19 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
                                                                                             Write(studentUSI);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n        $(\"#Metric");


            
            #line 20 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
              Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("-EdFiGrid-interaction-custom\").append($(\"#buttonExportAll-");


            
            #line 20 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
                                                                                          Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\"));\r\n        $(\"#buttonExportAll-");


            
            #line 21 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
                        Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\").show();\r\n    </script>\r\n    <a href=\"");


            
            #line 23 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
        Write(Url.Action("Get", "LearningObjectivesExport"));

            
            #line default
            #line hidden
WriteLiteral("\" id=\"buttonExportAll-");


            
            #line 23 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
                                                                             Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn\" style=\"display:none;\"><i class=\"icon-floppy\"></i> EXPORT ALL</a>\r\n " +
"   <a href=\"");


            
            #line 24 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
        Write(Url.Action("Get", "LearningObjectivesExport"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"hidden\">Export learning objectives for metric ");


            
            #line 24 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
                                                                                                              Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral(" to csv</a>\r\n");


            
            #line 25 "..\..\Areas\StudentSchool\Views\Detail\LearningObjectivesTable\Get.cshtml"
      Html.RenderPartial("EdFiGrid", model: edfiGridModel);

            
            #line default
            #line hidden
WriteLiteral("</div>");


        }
    }
}
#pragma warning restore 1591
