// *************************************************************************
// ©2013 Ed-Fi Alliance, LLC. All Rights Reserved.
// *************************************************************************
using System.Web.Routing;

namespace EdFi.Dashboards.Resources.Navigation
{
    /// <summary>
    /// Prepares route values for outbound URL generation.
    /// </summary>
    public interface IRouteValuesPreparer
    {
        /// <summary>
        /// Prepares the route values so that the URL generated by the routing system for the specified route will be complete, and correct.
        /// </summary>
        /// <param name="routeName">The name of the registered route in the ASP.NET MVC <see cref="RouteTable"/>.</param>
        /// <param name="routeValues">The initial route values provided, to be used to prepare the final route value for URL generation.</param>
        void PrepareRouteValues(string routeName, RouteValueDictionary routeValues);

        /// <summary>
        /// Prepares the route values so that the URL generated by the routing system for the specified route will be complete, and correct.
        /// </summary>
        /// <param name="route">The route for which values are to be prepared.</param>
        /// <param name="routeValues">The initial route values provided, to be used to prepare the final route value for URL generation.</param>
        void PrepareRouteValues(Route route, RouteValueDictionary routeValues);
    }
}
