#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.LocalEducationAgency.Views.Detail.SchoolMetricTable
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
    using EdFi.Dashboards.Common.Utilities;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
    using EdFi.Dashboards.Core.Providers.Context;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line 3 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Providers.Models;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    #line 4 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
    using EdFi.Dashboards.Resources.Navigation.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/LocalEducationAgency/Views/Detail/SchoolMetricTable/Get.cshtml")]
    public partial class Get : System.Web.Mvc.WebViewPage<EdFi.Dashboards.Resources.Models.CustomGrid.GridTable>
    {
        public Get()
        {
        }
        public override void Execute()
        {





WriteLiteral("         \r\n");


            
            #line 7 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
  
    var localEducationAgencyId = EdFiDashboardContext.Current.LocalEducationAgencyId.GetValueOrDefault();
    var metricVariantId = EdFiDashboardContext.Current.MetricVariantId.GetValueOrDefault();

    var edFiGridModelProvider = IoC.Resolve<IEdFiGridModelProvider>();

    var edfiGridModel = edFiGridModelProvider.GetEdFiGridModel(true, false, 10, "Metric" + metricVariantId, metricVariantId, Model,
        null, Model.GetDefaultNonPersistedSettings("Metric" + metricVariantId + "EdFiGrid"), false, "SchoolList", null, "metricContext", false, null, false);


            
            #line default
            #line hidden
WriteLiteral("<div id=\"SchoolMetricTable");


            
            #line 16 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
                      Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    <script type=\"text/javascript\" language=\"javascript\">\r\n        analyticsM" +
"anager.trackDrilldown(\'LocalEducationAgencySchoolMetricTable\', \'");


            
            #line 18 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
                                                                              Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\', \'");


            
            #line 18 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
                                                                                                    Write(localEducationAgencyId);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n        $(\"#Metric");


            
            #line 19 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
              Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("-EdFiGrid-interaction-custom\").append($(\"#buttonExportAll-");


            
            #line 19 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
                                                                                          Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\"));\r\n        $(\"#buttonExportAll-");


            
            #line 20 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
                        Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\").show();\r\n    </script>\r\n    <a href=\"#\" onclick=\"ExportLocalEducationAgencySch" +
"oolMetricList(");


            
            #line 22 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
                                                                Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral(", \'");


            
            #line 22 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
                                                                                     Write(EdFiDashboards.Site.LocalEducationAgency.ExportMetricList(localEducationAgencyId, metricVariantId, new { format = "csv" }));

            
            #line default
            #line hidden
WriteLiteral("\');(event.preventDefault) ? event.preventDefault() : event.returnValue = false;\" " +
"id=\"buttonExportAll-");


            
            #line 22 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
                                                                                                                                                                                                                                                                                                                       Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn\" style=\"display:none;\"><i class=\"icon-floppy\"></i> EXPORT ALL</a>\r\n " +
"   <a href=\"#\" onclick=\"ExportLocalEducationAgencySchoolMetricList(");


            
            #line 23 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
                                                                Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral(", \'");


            
            #line 23 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
                                                                                     Write(EdFiDashboards.Site.LocalEducationAgency.ExportMetricList(localEducationAgencyId, metricVariantId, new { format = "csv" }));

            
            #line default
            #line hidden
WriteLiteral("\');(event.preventDefault) ? event.preventDefault() : event.returnValue = false;\" " +
"class=\"hidden\">Export learning objectives for metric ");


            
            #line 23 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
                                                                                                                                                                                                                                                                                                                                                        Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral(" to csv</a>\r\n");


            
            #line 24 "..\..\Areas\LocalEducationAgency\Views\Detail\SchoolMetricTable\Get.cshtml"
      Html.RenderPartial("EdFiGrid", model: edfiGridModel);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
