#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Views.MetricTemplates.StudentSchool.Metric
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MetricTemplates/StudentSchool/Metric/AggregateMetric.Level1.ParentMetricI" +
        "d_95.cshtml")]
    public class AggregateMetric_Level1_ParentMetricId_95 : System.Web.Mvc.WebViewPage<AggregateMetric>
    {
        public AggregateMetric_Level1_ParentMetricId_95()
        {
        }
        public override void Execute()
        {



            #line 2 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
  
    //Define the ParentContainerMetricId to propagate fo the unique columns.
    //This si needed because we have "Complex tables" meaning colspans that then need unique ids in the headers and matching the cells in the rows below with the same headers="uniqueColumnId". 
    this.SetMetricRenderingContextValue("ParentContainerMetricId", Model.MetricId);
    this.SetMetricRenderingContextValue("colCount", 5);
            

            
            #line default
            #line hidden
WriteLiteral("<!-- Inline Style is left intentionally in the MetricTemplate to provide a easyer" +
" way to override.-->\r\n<table summary=\"This table displays metrics regarding ");


            
            #line 9 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                                                  Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral(".\">\r\n<thead>\r\n    <tr id=\"vMetric");


            
            #line 11 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
               Write(Model.MetricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\">    \r\n        <th id=\"MetricName");


            
            #line 12 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                      Write(this.GetMetricRenderingContextValue("ParentContainerMetricId"));

            
            #line default
            #line hidden
WriteLiteral("\" style=\"width: 45%;\" title=\"");


            
            #line 12 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                                                                                                                   Write(Model.ToolTip);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <span id=\"vMetricVariantId");


            
            #line 13 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                                  Write(Model.MetricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"metricId\">\r\n                ");


            
            #line 14 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
            Write(Model.MetricId);

            
            #line default
            #line hidden
WriteLiteral("-");


            
            #line 14 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                              Write(Model.MetricVariantType);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </span>\r\n            <a name=\"");


            
            #line 16 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                 Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 16 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                                       Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            <a name=\"m");


            
            #line 17 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                  Write(Model.MetricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\">&nbsp;</a>\r\n        </th>\r\n        <th id=\"MetricState");


            
            #line 19 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                       Write(this.GetMetricRenderingContextValue("ParentContainerMetricId"));

            
            #line default
            #line hidden
WriteLiteral("\" style=\"width: 15%;\" title=\"Color indicates if meeting student goal\">\r\n         " +
"   Status\r\n        </th>\r\n        <th id=\"MetricValue");


            
            #line 22 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                       Write(this.GetMetricRenderingContextValue("ParentContainerMetricId"));

            
            #line default
            #line hidden
WriteLiteral("\" style=\"width: 18%;\" title=\"Color indicates if meeting student goal\">\r\n         " +
"   Metric Value\r\n        </th>\r\n        <th id=\"MetricTrend");


            
            #line 25 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                       Write(this.GetMetricRenderingContextValue("ParentContainerMetricId"));

            
            #line default
            #line hidden
WriteLiteral("\" style=\"width: 5%;\" title=\"Comparison from prior period\">\r\n            Trend\r\n  " +
"      </th>\r\n        <th id=\"MetricDetails");


            
            #line 28 "..\..\Views\MetricTemplates\StudentSchool\Metric\AggregateMetric.Level1.ParentMetricId_95.cshtml"
                         Write(this.GetMetricRenderingContextValue("ParentContainerMetricId"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"doNotPrint\" style=\"text-align:center;\">\r\n            Details\r\n        </" +
"th>\r\n    </tr>\r\n</thead>\r\n<tbody>");


        }
    }
}
#pragma warning restore 1591
