#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Views.MetricTemplates.School.Metric
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MetricTemplates/School/Metric/GranularMetric.Close.Level2.MetricId_1484.M" +
        "etricVariantType_CurrentYear.cshtml")]
    public class GranularMetric_Close_Level2_MetricId_1484_MetricVariantType_CurrentYear : System.Web.Mvc.WebViewPage<MetricBase>
    {
        public GranularMetric_Close_Level2_MetricId_1484_MetricVariantType_CurrentYear()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\MetricTemplates\School\Metric\GranularMetric.Close.Level2.MetricId_1484.MetricVariantType_CurrentYear.cshtml"
Write(Html.Partial("DynamicContentDiv", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
