#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.Staff.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Staff\Views\Shared\_AreaLayout.cshtml"
    using EdFi.Dashboards.Core.Providers.Context;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    
    #line 2 "..\..\Areas\Staff\Views\Shared\_AreaLayout.cshtml"
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Utilities;
    
    #line 3 "..\..\Areas\Staff\Views\Shared\_AreaLayout.cshtml"
    using EdFi.Dashboards.Resources.Navigation;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Staff\Views\Shared\_AreaLayout.cshtml"
    using EdFi.Dashboards.Resources.Navigation.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Staff/Views/Shared/_AreaLayout.cshtml")]
    public class AreaLayout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public AreaLayout()
        {
        }
        public override void Execute()
        {





            
            #line 5 "..\..\Areas\Staff\Views\Shared\_AreaLayout.cshtml"
  
    //ViewBag.Title = "Staff";
	Layout = this.GetLayout("_SiteLayout");


            
            #line default
            #line hidden
WriteLiteral("\n");


DefineSection("head", () => {

WriteLiteral(@"
    <script type=""text/javascript"">
        function GoToSchool(dropdown) {
            var schoolUrl = $(dropdown).val();
            NavigateToPage(schoolUrl);
        }

        function GoToView(dropdown) {
            var viewUrl = $(dropdown).val();
            NavigateToPage(viewUrl);
        }

        function GoToSection(dropdown) {
            var viewUrl = $(dropdown).val();
            NavigateToPage(viewUrl);
        }

    </script>


	");


            
            #line 30 "..\..\Areas\Staff\Views\Shared\_AreaLayout.cshtml"
Write(RenderSection("ContentPlaceHolderHead", required: false));

            
            #line default
            #line hidden
WriteLiteral("\n");


});

WriteLiteral("\n\n");


DefineSection("ContentDataHeader", () => {

WriteLiteral("\n");


            
            #line 34 "..\..\Areas\Staff\Views\Shared\_AreaLayout.cshtml"
      Html.RenderAction("StaffHeader", "StaffLayout");

            
            #line default
            #line hidden

});

WriteLiteral("\n\n");


DefineSection("ContentMenu", () => {

WriteLiteral("\n    <div id=\"StaffSlidingMenuHome\">\n        <div id=\"StaffSlidingSubmenu\">\n");


            
            #line 40 "..\..\Areas\Staff\Views\Shared\_AreaLayout.cshtml"
              Html.RenderAction("Menu", "StaffLayout");

            
            #line default
            #line hidden
WriteLiteral("        </div>\n    </div>\n");


});

WriteLiteral("\n\n");


DefineSection("ContentPlaceHolderTopMost", () => {

WriteLiteral("\n<div class=\"l-area-layout\">\n    ");


            
            #line 47 "..\..\Areas\Staff\Views\Shared\_AreaLayout.cshtml"
Write(RenderSection("ContentPlaceHolder1", required: false));

            
            #line default
            #line hidden
WriteLiteral("\n</div>\n<!-- PageContext hidden field -->\n<input type=\"hidden\" name=\"PageContext\"" +
" value=\"TeacherClassroom\" />\n<script type=\"text/javascript\" language=\"javascript" +
"\">\r\n    analyticsManager.trackDataView(\'");


            
            #line 52 "..\..\Areas\Staff\Views\Shared\_AreaLayout.cshtml"
                               Write(EdFiDashboardContext.Current.StaffUSI);

            
            #line default
            #line hidden
WriteLiteral("\');\n\n    var menuDisplayed = false;\n    var allowMenuAction = true;\n</script>\n<!-" +
"- The ToolTip -->\n<div id=\"JQToolTip\"></div>\n");


});


        }
    }
}
#pragma warning restore 1591
