#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.Staff.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
    using EdFi.Dashboards.Core.Providers.Context;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    
    #line 2 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Utilities;
    
    #line 6 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
    using EdFi.Dashboards.Resources.Models.Common;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
    using EdFi.Dashboards.Resources.Navigation;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
    using EdFi.Dashboards.Resources.Navigation.Mvc;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
    using EdFi.Dashboards.Resources.Navigation.Support;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Staff/Views/Shared/Menu.cshtml")]
    public partial class Menu : System.Web.Mvc.WebViewPage<EdFi.Dashboards.Presentation.Core.Areas.Staff.Models.StaffMenuModel>
    {

public System.Web.WebPages.HelperResult BuildViewsDropdown(IEnumerable<EdFi.Dashboards.Resources.Models.Staff.StaffModel.View> views, string listContext)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 11 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
 
    foreach (var view in views)
    {
        var padding = string.Format("{0}px", (10 * view.MenuLevel) + 5);                   
                    
        if (view.ChildViews.Count == 0)
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            <option style=\"padding-left: ");



#line 18 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
          WriteTo(@__razor_helper_writer, padding);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" value=\"");



#line 18 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
                            WriteTo(@__razor_helper_writer, view.Link.Href.AppendParameters(listContext));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"\r\n");



#line 19 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
                 if (view.Selected)
                {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    ");

WriteLiteralTo(@__razor_helper_writer, "selected=\'selected\' \r\n");



#line 22 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
                }
#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " >\r\n                ");



#line 23 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
WriteTo(@__razor_helper_writer, view.Description);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n            </option>\r\n");



#line 25 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
        }
        else
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            <optgroup style=\"padding-left: ");



#line 28 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
            WriteTo(@__razor_helper_writer, padding);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "; font-weight:normal;\" label=\"");



#line 28 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
                                                  WriteTo(@__razor_helper_writer, view.Description);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n            ");



#line 29 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
WriteTo(@__razor_helper_writer, BuildViewsDropdown(view.ChildViews, listContext));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ";\r\n            </optgroup>\r\n");



#line 31 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
        }
    }

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult BuildStudentListDropDown(IEnumerable<EdFi.Dashboards.Resources.Models.Staff.StaffModel.SectionOrCohort> sections, string listContext)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 35 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
 
    foreach (var section in sections)
    {
        if (section.ChildSections.Count == 0)
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            <option value=\"");



#line 40 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
WriteTo(@__razor_helper_writer, section.Link.Href.AppendParameters(listContext));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"\r\n");



#line 41 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
                 if (section.Selected)
                {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "                    ");

WriteLiteralTo(@__razor_helper_writer, "selected=\'selected\'\r\n");



#line 44 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
                }
#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " >\r\n                ");



#line 45 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
WriteTo(@__razor_helper_writer, section.Description);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\r\n            </option>\r\n");



#line 47 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
        }
        else
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "            <optgroup label=\"");



#line 50 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
WriteTo(@__razor_helper_writer, section.Description);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">\r\n                ");



#line 51 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
WriteTo(@__razor_helper_writer, BuildStudentListDropDown(section.ChildSections, listContext));

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, ";\r\n            </optgroup>\r\n");



#line 53 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
        }
    }

#line default
#line hidden

});

}


        public Menu()
        {
        }
        public override void Execute()
        {






WriteLiteral("\r\n");


WriteLiteral("\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");


            
            #line 57 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
  
    bool showSchool = (Model != null && Model.Schools != null && Model.Schools.Count > 1);
    string ListContext = "";
    if (!string.IsNullOrEmpty(Request.QueryString["listContext"]))
    {
        ListContext = ("listContext=" + Request.QueryString["listContext"]);
    }


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 66 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
  
    var context = EdFiDashboardContext.Current;
    string separatorGrayThinUrl = EdFiDashboards.Site.Common.ThemeImage("SeparatorGrayThin.gif").Resolve();
    var isAssessmentDetailsView = EdFiDashboardContext.Current.ViewType == EdFi.Dashboards.Resources.Models.Staff.StaffModel.ViewType.AssessmentDetails.ToString();
    var assessmentSubType = Model.AssessmentSubTypeValue;


            
            #line default
            #line hidden


WriteLiteral("\r\n<ul class=\"section-menu\">\r\n");


            
            #line 74 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
     if (showSchool)
    {

            
            #line default
            #line hidden
WriteLiteral("    <li><label for=\"schoolSelect\">School:</label>\r\n        <select id=\"schoolSele" +
"ct\" onchange=\"GoToSchool(this);\" style=\"width: 100px;\">\r\n");


            
            #line 78 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
             foreach (var school in Model.Schools)
            {

            
            #line default
            #line hidden
WriteLiteral("                <option value=\"");


            
            #line 80 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
                           Write(school.Link.Href.AppendParameters(ListContext));

            
            #line default
            #line hidden
WriteLiteral("\" \r\n");


            
            #line 81 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
                     if (school.Selected)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("selected=\'selected\' \r\n");


            
            #line 84 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
                    }
            
            #line default
            #line hidden
WriteLiteral(" >\r\n                    ");


            
            #line 85 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
               Write(school.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </option>\r\n");


            
            #line 87 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </select>\r\n    </li>\r\n");


            
            #line 90 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
    }

            
            #line default
            #line hidden

            
      
    

            
            #line default
            #line hidden
WriteLiteral("    <li><label for=\"sectionSelect\">Student List:</label>\r\n        <select id=\"sec" +
"tionSelect\" onchange=\"GoToSection(this);\" style=\"width: 470px;\">\r\n            ");


            
            #line 96 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
       Write(BuildStudentListDropDown(Model.SectionsAndCohorts, ListContext));

            
            #line default
            #line hidden
WriteLiteral(";\r\n        </select>\r\n    </li>\r\n    <li><label for=\"viewSelect\">Data View:</labe" +
"l>\r\n        <select id=\"viewSelect\" onchange=\"GoToView(this);\" style=\"width: 170" +
"px;\">\r\n            ");


            
            #line 101 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
       Write(BuildViewsDropdown(Model.Views.Where(v => v.MenuLevel == 0), ListContext));

            
            #line default
            #line hidden
WriteLiteral(";\r\n        </select>\r\n    </li>\r\n</ul>\r\n<script type=\"text/javascript\">\r\n    func" +
"tion exportAll_Click() {\r\n        analyticsManager.trackExport(\'Staff\', \'All\');\r" +
"\n\r\n      if (\"");


            
            #line 109 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
      Write(isAssessmentDetailsView);

            
            #line default
            #line hidden
WriteLiteral("\" == \"True\") {\r\n          window.location = \'");


            
            #line 110 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
                         Write(new HtmlString(EdFiDashboards.Site.Staff.ExportAllMetrics(EdFiDashboardContext.Current.SchoolId.GetValueOrDefault(), EdFiDashboardContext.Current.StaffUSI.GetValueOrDefault(), null, (EdFiDashboardContext.Current.SectionOrCohortId ?? 0) == 0 ? null : EdFiDashboardContext.Current.SectionOrCohortId, (EdFiDashboardContext.Current.SectionOrCohortId ?? 0) == 0 ? "All" : EdFiDashboardContext.Current.StudentListType, EdFiDashboardContext.Current.SubjectArea, @assessmentSubType, new { format = "csv", SubjectArea = EdFiDashboardContext.Current.SubjectArea })));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n      }\r\n      else {\r\n          window.location = \'");


            
            #line 113 "..\..\Areas\Staff\Views\Shared\Menu.cshtml"
                         Write(new HtmlString(EdFiDashboards.Site.Staff.ExportAllMetrics(EdFiDashboardContext.Current.SchoolId.GetValueOrDefault(), EdFiDashboardContext.Current.StaffUSI.GetValueOrDefault(), null, (EdFiDashboardContext.Current.SectionOrCohortId ?? 0) == 0 ? null : EdFiDashboardContext.Current.SectionOrCohortId, (EdFiDashboardContext.Current.SectionOrCohortId ?? 0) == 0 ? "All" : EdFiDashboardContext.Current.StudentListType, null, null, new { format = "csv" })));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n      }\r\n  }\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
