// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "systemSupport", Scope = "member", Target = "EdFi.Dashboards.Resources.LocalEducationAgency.LocalEducationAgencyContextGradingPeriodProvider.#GetOrganization(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "StudentMetricAbsencesByClass", Scope = "member", Target = "EdFi.Dashboards.Resources.StudentSchool.Detail.ClassAbsencesService.#Get(EdFi.Dashboards.Resources.StudentSchool.Detail.ClassAbsencesRequest)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "U", Scope = "type", Target = "EdFi.Dashboards.Resources.Application.InMemoryPersistingRepository`2")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "U", Scope = "type", Target = "EdFi.Dashboards.Resources.Application.FileSystemBasedPersistingRepository`2")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Whitelist", Scope = "member", Target = "EdFi.Dashboards.Resources.Search.QuickSearchRequest.#ViewAllTeacherWhitelistSchoolIds")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Whitelist", Scope = "member", Target = "EdFi.Dashboards.Resources.Search.SearchRequest.#Create(System.String,System.Int32,System.Boolean,EdFi.Dashboards.Resources.Search.SearchFilter,System.Int32[],System.Nullable`1<System.Int32>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Whitelist", Scope = "member", Target = "EdFi.Dashboards.Resources.Search.SearchRequest.#ViewAllTeacherWhitelistSchoolIds")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.StudentSchool.IAccommodationProvider.#GetAccommodations(System.Int32[],System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "ContainerMetric", Scope = "member", Target = "EdFi.Dashboards.Resources.LocalEducationAgency.ExportAllMetricsService.#GetFlattenedOutMetrics(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "castable", Scope = "member", Target = "EdFi.Dashboards.Resources.LocalEducationAgency.ExportAllMetricsService.#GetFlattenedOutMetrics(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "ContainerMetric", Scope = "member", Target = "EdFi.Dashboards.Resources.School.ExportAllMetricsService.#GetFlattenedOutMetrics(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "castable", Scope = "member", Target = "EdFi.Dashboards.Resources.School.ExportAllMetricsService.#GetFlattenedOutMetrics(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "writing", Scope = "member", Target = "EdFi.Dashboards.Resources.Staff.AssessmentDetailsServiceBase`3.#writing")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "social", Scope = "member", Target = "EdFi.Dashboards.Resources.Staff.AssessmentDetailsServiceBase`3.#socialStudies")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "science", Scope = "member", Target = "EdFi.Dashboards.Resources.Staff.AssessmentDetailsServiceBase`3.#science")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "mathematics", Scope = "member", Target = "EdFi.Dashboards.Resources.Staff.AssessmentDetailsServiceBase`3.#mathematics")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "ela", Scope = "member", Target = "EdFi.Dashboards.Resources.Staff.AssessmentDetailsServiceBase`3.#elaReading")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "ela", Scope = "member", Target = "EdFi.Dashboards.Resources.Staff.AssessmentDetailsServiceBase`3.#elaReading")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "StudentMetricAbsencesByClass", Scope = "member", Target = "EdFi.Dashboards.Resources.StudentSchool.Detail.ClassAbsencesServiceBase`2.#Get(!0)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "jira", Scope = "member", Target = "EdFi.Dashboards.Resources.Application.FeedbackService.#Post(EdFi.Dashboards.Resources.Application.FeedbackRequest)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "defaultProjectName", Scope = "member", Target = "EdFi.Dashboards.Resources.Application.FeedbackService.#Post(EdFi.Dashboards.Resources.Application.FeedbackRequest)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.StudentSchool.IAccommodationProvider.#GetAccommodations(System.Int64[],System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ssis", Scope = "type", Target = "EdFi.Dashboards.Resources.Metric.MetricInstanceSetKeyResolvers.SsisMultiHashMetricInstanceSetKeyResolver`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "type", Target = "EdFi.Dashboards.Resources.Metric.MetricInstanceSetKeyResolvers.SsisMultiHashMetricInstanceSetKeyResolver`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Api", Scope = "member", Target = "EdFi.Dashboards.Resources.Navigation.ILocalEducationAgencyAreaLinks.#ApiResource(System.Int32,System.Object,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Api", Scope = "member", Target = "EdFi.Dashboards.Resources.Navigation.ILocalEducationAgencyAreaLinks.#ApiResource(System.Int32,System.Object,System.String,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Api", Scope = "member", Target = "EdFi.Dashboards.Resources.Navigation.SiteAreaBase.#BuildApiResourceUrl(System.Object,System.Reflection.MethodBase,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Api", Scope = "member", Target = "EdFi.Dashboards.Resources.Navigation.SiteAreaBase.#BuildApiResourceUrl(System.Object,System.String,System.Reflection.MethodBase,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Unshare", Scope = "type", Target = "EdFi.Dashboards.Resources.Common.IMetricsBasedWatchListUnshareService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Unshare", Scope = "type", Target = "EdFi.Dashboards.Resources.Common.MetricsBasedWatchListUnshareService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Unshare", Scope = "type", Target = "EdFi.Dashboards.Resources.Common.MetricsBasedWatchListUnshareRequest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Convertable", Scope = "type", Target = "EdFi.Dashboards.Resources.Common.IEdFiGridMetaRequestConvertable")]
