#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.StudentSchool.Views.Detail.DaysAbsentList
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
    using EdFi.Dashboards.Core.Providers.Context;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    
    #line 2 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Architecture;
    using EdFi.Dashboards.Presentation.Web.Utilities;
    
    #line 3 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
    using EdFi.Dashboards.Resources.Navigation;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/StudentSchool/Views/Detail/DaysAbsentList/Get.cshtml")]
    public class Get : System.Web.Mvc.WebViewPage<IList<EdFi.Dashboards.Resources.Models.Student.Detail.DaysAbsentModel>>
    {
        public Get()
        {
        }
        public override void Execute()
        {




WriteLiteral("\r\n");


            
            #line 6 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
  
    var studentUSI = EdFiDashboardContext.Current.StudentUSI.GetValueOrDefault();
    var metricVariantId = EdFiDashboardContext.Current.MetricVariantId.GetValueOrDefault();


            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    analyticsManager.trackDrilldown(\'StudentDaysAbsentList\', \'");


            
            #line 12 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
                                                          Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\', \'");


            
            #line 12 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
                                                                                Write(studentUSI);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n</script>\r\n");


            
            #line 14 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
 if (Model.Any())
{

            
            #line default
            #line hidden
WriteLiteral(@"    <table class=""standard-table standard-table-compressed"" summary=""Table lists a detail of days absent."">		
        <thead>
            <tr>
                <th style=""text-align:left;"">Grading Period</th>
                <th>Excused Days</th>
                <th>Unexcused Days</th>
            </tr>
        </thead>
        <tbody>
");


            
            #line 25 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
         for (int i = 0; i < Model.Count(); i++)
        {
            var objective = Model[i];

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>\r\n                    <p class=\"arrow\">\r\n  " +
"                  <i class=\"icon-blank\"></i>\r\n                    <span class=\"M" +
"etricBulletTitle\">");


            
            #line 32 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
                                               Write(objective.Context);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </p>\r\n                </td>\r\n                <td>");


            
            #line 35 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
               Write(objective.ExcusedDays);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");


            
            #line 36 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
               Write(objective.UnexcusedDays);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n");

            

            #line 38 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");


            
            #line 41 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <span class=\"MetricNoData\">No data available.</span>\r\n");


            
            #line 45 "..\..\Areas\StudentSchool\Views\Detail\DaysAbsentList\Get.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
