#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Views.MetricTemplates.School.GoalPlanning
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MetricTemplates/School/GoalPlanning/GranularMetric.Level2.Disabled.cshtml" +
        "")]
    public class GranularMetric_Level2_Disabled : System.Web.Mvc.WebViewPage<IGranularMetric>
    {
        public GranularMetric_Level2_Disabled()
        {
        }
        public override void Execute()
        {

WriteLiteral("<tr id=\"vMetric");


            
            #line 2 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
           Write(Model.MetricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"container\">\n    <td headers=\"MetricName");


            
            #line 3 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                       Write(this.GetMetricRenderingContextValue("ParentContainerMetricId"));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 3 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                                                                                                Write(Model.ToolTip);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"deemphasized\">\r\n        <span id=\"vMetricVariantId");


            
            #line 4 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                              Write(Model.MetricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"metricId\">\n            ");


            
            #line 5 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
        Write(Model.MetricId);

            
            #line default
            #line hidden
WriteLiteral("-");


            
            #line 5 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                          Write(Model.MetricVariantType);

            
            #line default
            #line hidden
WriteLiteral("\n        </span>\r\n        <h3 class=\"title deemphasized\">\n                <span i" +
"d=\"vName");


            
            #line 8 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                           Write(Model.MetricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\">\n                    <a id=\"");


            
            #line 9 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                      Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 9 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                                           Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</a> <span class=\"hidden\">(Disabled)</span>\n                </span>\n            <" +
"a id=\"m");


            
            #line 11 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                Write(Model.MetricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\"></a>\n");


            
            #line 12 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
             if (!String.IsNullOrWhiteSpace(Model.Context))
            {

            
            #line default
            #line hidden
WriteLiteral("                <span id=\"vContext");


            
            #line 14 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                              Write(Model.MetricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\">(");


            
            #line 14 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                                                        Write(Model.Context);

            
            #line default
            #line hidden
WriteLiteral(")</span>\n");


            
            #line 15 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </h3>\n        <span class=\"deemphasized\" id=\"vDescription");


            
            #line 17 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                                               Write(Model.MetricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\">\n            ");


            
            #line 18 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
       Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("\n        </span>\n    </td>\n    <td headers=\"MetricValue");


            
            #line 21 "..\..\Views\MetricTemplates\School\GoalPlanning\GranularMetric.Level2.Disabled.cshtml"
                        Write(this.GetMetricRenderingContextValue("ParentContainerMetricId"));

            
            #line default
            #line hidden
WriteLiteral("\" colspan=\"4\"></td>\n</tr>\n");


        }
    }
}
#pragma warning restore 1591
