// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "locationAuthorizationSection", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.MetricActionUrlAuthorizationProvider.#.ctor(EdFi.Dashboards.Infrastructure.IConfigSectionProvider)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "IClaimAuthorization", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.CastleWindsorInstallers.SecurityComponentsInstaller.#RegisterClaimAuthorizations(Castle.Windsor.IWindsorContainer,System.Collections.Generic.Dictionary`2<System.String,System.String>,System.Reflection.Assembly)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "claimValidator", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.ClaimValidators.ClaimAuthorizationBase.#.ctor(EdFi.Dashboards.Resources.Security.ClaimValidators.IClaimValidator)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "ClaimName", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.CastleWindsorInstallers.SecurityComponentsInstaller.#RegisterClaimAuthorizations(Castle.Windsor.IWindsorContainer,System.Collections.Generic.Dictionary`2<System.String,System.String>,System.Reflection.Assembly)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "ClaimAuthorization", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.CastleWindsorInstallers.SecurityComponentsInstaller.#RegisterClaimAuthorizations(Castle.Windsor.IWindsorContainer,System.Collections.Generic.Dictionary`2<System.String,System.String>,System.Reflection.Assembly)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "CanBeAuthorizedByAttribute", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.ApplyViewPermissionsByClaimInterceptor.#AuthorizeByAttribute(Castle.DynamicProxy.IInvocation)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Infos", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.ApplyViewPermissionsByClaimInterceptor.#GetParameterInstancesForValidation(System.Collections.Generic.IEnumerable`1<System.Reflection.ParameterInfo>,System.Collections.Generic.IEnumerable`1<System.Object>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.SecurityAssertionProvider.#GetStudentUSIsForTeacher(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.SecurityAssertionProvider.#GetStudentUSIsForSpecialist(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetTeacherStudentUSIs(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetStaffCohortStudentUSIs(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetSchoolStudentUSIs(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetSchoolStaffUSIs(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetPrincipalStudentUSIs(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetIQueryableForPrincipalStudentUSIs(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.AccessibleStudents.#StudentUSIs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetAllStaffStudentUSIs(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.AuthorizationInformationProvider.#GetIQueryableForStudentUSIsAtLocalEducationAgencyLevelClaims(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "locationAuthorizationSection", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.MetricActionUrlAuthorizationProvider.#.ctor(EdFi.Dashboards.Infrastructure.IConfigSectionProvider,EdFi.Dashboards.Resources.Security.Common.ICurrentUserClaimInterrogator)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetLocalEducationAgencyStaffUSIs(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "StudentGPS", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.StaffInformationProvider.#ResolveStaffUSI(EdFi.Dashboards.SecurityTokenService.Authentication.IAuthenticationProvider,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "StaffUSI", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.StaffInformationProvider.#ResolveUsername(EdFi.Dashboards.SecurityTokenService.Authentication.IAuthenticationProvider,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.AuthorizationInformationProvider.#GetIQueryableForStudentUSIsAtLocalEducationAgencyLevelClaims(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetAllStaffStudentUSIs(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetIQueryableForPrincipalStudentUSIs(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetPrincipalStudentUSIs(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetStaffCohortStudentUSIs(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.IAuthorizationInformationProvider.#GetTeacherStudentUSIs(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.SecurityAssertionProvider.#GetStudentUSIsForSpecialist(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.SecurityAssertionProvider.#GetStudentUSIsForTeacher(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Wctx", Scope = "type", Target = "EdFi.Dashboards.Resources.Security.Implementations.Base64WctxWimpProvider")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Wctx", Scope = "type", Target = "EdFi.Dashboards.Resources.Security.Implementations.WctxWimpProvider")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "ws", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.DashboardClaimsAuthenticationManagerProvider.#Get(System.String,Microsoft.IdentityModel.Claims.IClaimsPrincipal)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "emailaddress", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.DashboardClaimsAuthenticationManagerProvider.#Get(System.String,Microsoft.IdentityModel.Claims.IClaimsPrincipal)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "xmlsoap", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.DashboardClaimsAuthenticationManagerProvider.#Get(System.String,Microsoft.IdentityModel.Claims.IClaimsPrincipal)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "StudentGPS", Scope = "member", Target = "EdFi.Dashboards.Resources.Security.Implementations.StaffInformationFromEmailProvider.#ResolveStaffUSI(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Auth", Scope = "type", Target = "EdFi.Dashboards.Resources.Security.Implementations.TextFileAuthenticationProvider+AuthInfo")]
