#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.School.Views.StudentsByGrade
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
    using EdFi.Dashboards.Common;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    
    #line 2 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Areas.School.Controllers;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Utilities;
    
    #line 4 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
    using EdFi.Dashboards.Resources.Navigation;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
    using EdFi.Dashboards.Resources.Navigation.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/School/Views/StudentsByGrade/Get.cshtml")]
    public class Get : System.Web.Mvc.WebViewPage<EdFi.Dashboards.Resources.Models.School.StudentsByGradeModel>
    {
        public Get()
        {
        }
        public override void Execute()
        {






WriteLiteral("           \n");


            
            #line 8 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
  
    //ViewBag.Title = "Students By Grade";


            
            #line default
            #line hidden
WriteLiteral("\n");


DefineSection("ContentPlaceHolderHead", () => {

WriteLiteral("\n    <title>");


            
            #line 13 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
       Write(Html.Action("Title", typeof(SchoolLayoutController).GetControllerName(), new { subTitle = "Students By Grade" }));

            
            #line default
            #line hidden
WriteLiteral("</title>\n    <script type=\"text/javascript\">\r\n        var pageArea = { Area: \'sch" +
"ool\', Page: \'Students by Grade\' };\r\n    </script>\n");


});

WriteLiteral("\n\n");


DefineSection("ContentPlaceHolder1", () => {

WriteLiteral("\n");


            
            #line 20 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
      
        var squareBulletImageUrl = EdFiDashboards.Site.Common.ThemeImage("BulletBluesquare.gif").Resolve();
    

            
            #line default
            #line hidden
WriteLiteral(@"    <table style=""width: 100%"" cellpadding=""0"" cellspacing=""0"" border=""0"">
        <tr>
            <td style=""height: 23px;"">
                <table style=""width: 100%;"" cellpadding=""0"" cellspacing=""0"">
                    <tr>
                        <td style=""width: 10px;""></td>
                        <td>
                            <label id=""LabelPageTitle"" class=""PageTitleTextStyle"">
                                STUDENTS BY GRADE
                            </label>
                        </td>
                        <td style=""text-align: right;""></td>
                    </tr>
                    <tr class=""doNotPrint"">
                        <td style=""width: 10px;""></td>
                        <td>
                            <!-- Index links -->
                            <table>
                                <tr>
                                    <td style=""text-align: left;"">
                                        <a name=""topAnchor""></a>
                                        <span class=""ContentBoldTextStyle"" style=""vertical-align: middle;"">
                                            Jump to grade: 
                                        </span>
");


            
            #line 47 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                          
                                            var first = true;
                                        

            
            #line default
            #line hidden

            
            #line 50 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                         foreach (var grade in Model.Grades)
                                        {
                                            if (!first)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <span class=\"ContentBoldTextStyle" +
"\" style=\"vertical-align: middle;\">&nbsp;|&nbsp;</span>\n");


            
            #line 55 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                            <a class=\"LinkMenu\" href=\"#");


            
            #line 56 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                                                   Write(grade.GradeLevel);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 56 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                                                                       Write(grade.GradeLevel);

            
            #line default
            #line hidden
WriteLiteral("</a>\n");


            
            #line 57 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                            first = false;
                                        }

            
            #line default
            #line hidden
WriteLiteral(@"                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr style=""height: 10px"">
            <td></td>
        </tr>
        <tr>
            <td>
                <!-- Content -->
                <table id=""tableContainer"" cellpadding=""0"" cellspacing=""0"" width=""100%"">
                    <tr>
                        <td class=""HeaderTabGray1""></td>
                        <td class=""HeaderTabGrayBG"" align=""left"">
                            <table style=""width: 100%; height: 100%;"" class=""HeaderTabGrayText"" border=""0"">
                                <tr>
                                    <td style=""width: 330px; text-align: left;"">
                                        GRADES
                                    </td>
                                    <td align=""right""></td>
                                </tr>
                            </table>
                        </td>
                        <td class=""HeaderTabGray2""></td>
                    </tr>
                </table>
");


            
            #line 89 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                 foreach (var grade in Model.Grades)
                {

            
            #line default
            #line hidden
WriteLiteral(@"                    <table cellpadding=""0"" cellspacing=""0"" style=""width: 100%; height: 100%;"" border=""0"">
                        <tr style=""height: 10px;"">
                            <td colspan=""2""></td>
                        </tr>
                        <tr>
                            <td style=""width: 15px; text-align: right;""></td>
                            <td class=""MetricSubTitle"">
                                <a name=""");


            
            #line 98 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                     Write(grade.GradeLevel);

            
            #line default
            #line hidden
WriteLiteral("\">\n                                    <span class=\"MetricTitle\" id=\'vGrade");


            
            #line 99 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                                                    Write(grade.GradeLevel);

            
            #line default
            #line hidden
WriteLiteral("\'>\n                                        ");


            
            #line 100 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                    Write(grade.GradeLevel);

            
            #line default
            #line hidden
WriteLiteral("\n                                    </span>\n                                </a>" +
"\n                                <a href=\"#topAnchor\" title=\"Back to top.\">\n    " +
"                                <img src=\'");


            
            #line 104 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                          Write(EdFiDashboards.Site.Common.ThemeImage("BulletBlueArrowUp.gif").Resolve());

            
            #line default
            #line hidden
WriteLiteral(@"' style=""border-width: 0px;"" />
                                </a>
                            </td>
                        </tr>
                        <tr style=""height: 10px;"">
                            <td colspan=""2""></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <table cellpadding=""0"" cellspacing=""0"" style=""width: 100%"" border=""0"">
");


            
            #line 115 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                      
                                        var studentCount = 0;
                                    

            
            #line default
            #line hidden

            
            #line 118 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                     foreach (var student in grade.Students)
                                    {
                                        if (studentCount % 2 == 0)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            ");

WriteLiteral("<tr style=\"height: 18px;\">\n");


            
            #line 123 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                        }


            
            #line default
            #line hidden
WriteLiteral("                                        <td class=\"BulletMetricBG\">\n             " +
"                               <img src=\'");


            
            #line 126 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                                  Write(squareBulletImageUrl);

            
            #line default
            #line hidden
WriteLiteral("\' style=\"vertical-align: middle;\" /> \n                                        </t" +
"d>\n");



WriteLiteral("                                        <td class=\"SubMetricBG\" style=\"width: 45%" +
";\">\n                                            <a href=\"");


            
            #line 129 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                                 Write(student.Url);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"LinkBullet\">\n                                                ");


            
            #line 130 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                           Write(student.FullName);

            
            #line default
            #line hidden
WriteLiteral(" \n                                            </a> \n                             " +
"           </td>\n");



WriteLiteral("                                        <td style=\"width:18px;\"></td>\n");


            
            #line 134 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"

                                        if (studentCount % 2 == 1)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            ");

WriteLiteral("</tr>\n");



WriteLiteral("                                            <tr style=\"height: 5px;\">\n           " +
"                                     <td colspan=\"6\">\n                          " +
"                      </td>\n                                            </tr>\n");


            
            #line 142 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                        }
                                        studentCount++;
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    \n");


            
            #line 146 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                     if (studentCount % 2 == 1)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                            <td style=\"width:20px;\"></td>\n");



WriteLiteral("                                            <td style=\"width: 45%;\"></td>\n");



WriteLiteral("                                            <td style=\"width:18px;\"></td>\n");



WriteLiteral("                                        ");

WriteLiteral("</tr>\n");



WriteLiteral("                                        <tr style=\"height: 5px;\">\n               " +
"                             <td colspan=\"6\">\n                                  " +
"          </td>\n                                        </tr>\n");


            
            #line 156 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </table>\n                            </td>\n      " +
"                  </tr>\n                    </table>\n");


            
            #line 161 "..\..\Areas\School\Views\StudentsByGrade\Get.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </td>\n        </tr>\n        <tr>\n            <td>\n                <hr" +
" class=\"End\" />\n            </td>\n        </tr>\n    </table>\n");


});

WriteLiteral("\n");


        }
    }
}
#pragma warning restore 1591
