// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "systemSupport", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Providers.Context.HttpRequestLocalEducationAgencyContextProvider.#InternalGetCode()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "RouteBase", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Providers.Context.HttpRequestLocalEducationAgencyContextProvider.#GetRequestUrlBase(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "RouteBase", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Controllers.PreviousNextController.#GetRequestUrlBase(System.Web.HttpContextBase)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "RouteBase", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Architecture.DashboardContextActionFilter.#GetRequestUrlBase(System.Web.Mvc.ActionExecutingContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "operationalDashboardSubtype", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Architecture.ValueProviders.MetricIdFromOperationalDashboardSubtypeValueProvider.#GetValue(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "jQuery", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Application.Student.Detail.LearningStandardsTable.#PerformDataBinding()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "jQuery", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Application.School.Detail.StudentMetricTable.#PerformDataBinding()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "jQuery", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Application.School.Detail.StaffMetricTable.#PerformDataBinding()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "jQuery", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Application.LocalEducationAgency.Detail.SchoolMetricTable.#PerformDataBinding()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "GridData", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Application.Student.Detail.LearningStandardsTable.#PerformDataBinding()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "GridData", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Application.School.Detail.StudentMetricTable.#PerformDataBinding()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "GridData", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Application.School.Detail.StaffMetricTable.#PerformDataBinding()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "GridData", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Application.LocalEducationAgency.Detail.SchoolMetricTable.#PerformDataBinding()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Db", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Utilities.CastleWindsor.ConfigurationSpecificInstallerBase.#RegisterIDbConnectionStringSelector(Castle.Windsor.IWindsorContainer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Recursed", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Utilities.CastleWindsor.ConfigurationSpecificInstallerBase.#OrderDependencies(System.Collections.Generic.List`1<System.Type>,System.Collections.Generic.List`1<System.Type>,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Architecture.HtmlHelperExtensions.BarChart.#.ctor(EdFi.Dashboards.Resources.Models.Charting.ChartData,System.Int32,System.Int32,System.Double,System.Int32,System.Nullable`1<System.Double>,System.String,System.Boolean,System.String,System.String,System.Web.UI.DataVisualization.Charting.SeriesChartType,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Architecture.HtmlHelperExtensions.BarChart.#.ctor(EdFi.Dashboards.Resources.Models.Charting.ChartData,System.Int32,System.Int32,System.Double,System.Int32,System.Nullable`1<System.Double>,System.String,System.Boolean,System.String,System.String,System.Web.UI.DataVisualization.Charting.SeriesChartType,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Architecture.HtmlHelperExtensions.Html.#BarChart(System.Web.Mvc.HtmlHelper,EdFi.Dashboards.Resources.Models.Charting.ChartData,System.Int32,System.Int32,System.Double,System.Int32,System.Nullable`1<System.Double>,System.String,System.Boolean,System.String,System.String,System.Web.UI.DataVisualization.Charting.SeriesChartType,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Architecture.HtmlHelperExtensions.Html.#BarChart(System.Web.Mvc.HtmlHelper,EdFi.Dashboards.Resources.Models.Charting.ChartData,System.Int32,System.Int32,System.Double,System.Int32,System.Nullable`1<System.Double>,System.String,System.Boolean,System.String,System.String,System.Web.UI.DataVisualization.Charting.SeriesChartType,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "OK", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Architecture.HttpStatusCode.#OK")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Areas.Staff.Controllers.StaffCohortController.#Post(System.Int32,System.Int32,System.Nullable`1<System.Int32>,System.String,System.Int32[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "PostHandler", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Controllers.AutoWired.HttpVerbHandlerPassthroughControllerBase`1.#CreateActionResult(!0)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Src", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Models.Shared.EdFiGridLegendModel.#ImageSrc")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "SchoolId", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Areas.School.Controllers.SchoolLayoutController.#Menu()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "SchoolLayoutController", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Areas.School.Controllers.SchoolLayoutController.#Menu()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "Desarrollado", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Utilities.GridTableHelper.#GetTejasLEEAssessmentDetailLegend()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "Nivel", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Utilities.GridTableHelper.#GetTejasLEEAssessmentDetailLegend()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "esperado", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Utilities.GridTableHelper.#GetTejasLEEAssessmentDetailLegend()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "intervención", Scope = "member", Target = "EdFi.Dashboards.Presentation.Web.Utilities.GridTableHelper.#GetTejasLEEAssessmentDetailLegend()")]
