#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.School.Views.Teachers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\School\Views\Teachers\Get.cshtml"
    using EdFi.Dashboards.Common;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\School\Views\Teachers\Get.cshtml"
    using EdFi.Dashboards.Common.Utilities;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line 3 "..\..\Areas\School\Views\Teachers\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Areas.School.Controllers;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\School\Views\Teachers\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Providers.Models;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/School/Views/Teachers/Get.cshtml")]
    public partial class Get : System.Web.Mvc.WebViewPage<EdFi.Dashboards.Resources.Models.CustomGrid.GridTable>
    {
        public Get()
        {
        }
        public override void Execute()
        {




WriteLiteral("\n");


WriteLiteral("         \n");


DefineSection("ContentPlaceHolderHead", () => {

WriteLiteral("\n    <title>");


            
            #line 9 "..\..\Areas\School\Views\Teachers\Get.cshtml"
       Write(Html.Action("Title", typeof(SchoolLayoutController).GetControllerName(), new { subTitle = "Teacher List" }));

            
            #line default
            #line hidden
WriteLiteral("</title>\n    <script>\n        var pageArea = { Area: \'school\', Page: \'Teacher Lis" +
"t\' };\r\n    </script>\n");


});

WriteLiteral("\n\n");


DefineSection("ContentPlaceHolder1", () => {

WriteLiteral("\n    <h2>Teacher List</h2>\n    \n");


            
            #line 18 "..\..\Areas\School\Views\Teachers\Get.cshtml"
         
           var edFiGridModelProvider = IoC.Resolve<IEdFiGridModelProvider>();

           var edfiGridModel = edFiGridModelProvider.GetEdFiGridModel(true, true, 0, "TeacherList",
               null, Model, null, null, true, "TeacherList", null, null, false, null, false);

    

            
            #line default
            #line hidden

            
            #line 25 "..\..\Areas\School\Views\Teachers\Get.cshtml"
      Html.RenderPartial("EdFiGrid", model: edfiGridModel);

            
            #line default
            #line hidden

});


        }
    }
}
#pragma warning restore 1591
