// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.ClaimValidators.AuthorizationFixtureBase.#GetStudentUSIsParameter(System.Int32[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.StudentFilter.When_servicing_student_data_base.#providedUserAllowedStudentUSIs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.StudentFilter.When_servicing_student_data_base.#allStudentUSIs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.ClaimValidators.AuthorizationFixtureBase.#ExpectGetSchoolStudentUSIsValidValid()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.ClaimValidators.AuthorizationFixtureBase.#ExpectGetSchoolStudentUSIsValidInvalid()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.ClaimValidators.AuthorizationFixtureBase.#ExpectGetSchoolStudentUSIsInvalidValid()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.ClaimValidators.AuthorizationFixtureBase.#ExpectGetSchoolStudentUSIsInvalidInvalid()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.ApplyViewPermissionsInterceptorContext.ApplyViewPermissionsByClaimFixtureBase.#ExpectGetStaffCohortStudentUSIsValidRepeatAny()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Namer", Scope = "type", Target = "EdFi.Dashboards.Resources.Tests.NonDefaultNonRepeatingPropertyNamer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.StudentFilter.When_getting_accessible_students_for_the_current_user.#SuppliedStudentUSIsForEdOrgViewAllStudents")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.StudentFilter.When_getting_accessible_students_for_the_current_user.#SuppliedStudentUSIsForEdOrgViewMyStudents")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.StudentFilter.When_getting_accessible_students_for_the_current_user.#SuppliedStudentUSIsForLEA")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.StudentFilter.When_getting_accessible_students_for_the_current_user.#SuppliedStudentUSIsForSearchClaim")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "USIs", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.ClaimValidators.AuthorizationFixtureBase.#GetStudentUSIsParameter(System.Int64[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Auth", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.ExplicitServiceLayerMethodClaimCoverageFixtureBase.#metricActionUrlAuthService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Auth", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.MetricFilter.MetricFilterFixtureBase.#metricActionUrlAuthService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Auth", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.Security.MetricFilter.When_loading_metric_actions.#metricActionUrlAuthService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Auth", Scope = "member", Target = "EdFi.Dashboards.Resources.Tests.All_services_should_return_serializable_models.#metricActionUrlAuthService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "type", Target = "EdFi.Dashboards.Resources.Tests.Metric.When_resolving_the_metric_instance_set_key_for_a_local_education_agency_metric_set_created_using_the_SSIS_Multi_Hash_component")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "type", Target = "EdFi.Dashboards.Resources.Tests.Metric.When_resolving_the_metric_instance_set_key_for_a_school_metric_set_created_using_the_SSIS_Multi_Hash_component")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "type", Target = "EdFi.Dashboards.Resources.Tests.Metric.When_resolving_the_metric_instance_set_key_for_a_student_school_metric_set_created_using_the_SSIS_Multi_Hash_component")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "th", Scope = "type", Target = "EdFi.Dashboards.Resources.Tests.School.When_listing_students_by_12th_grade")]