// *************************************************************************
// ©2013 Ed-Fi Alliance, LLC. All Rights Reserved.
// *************************************************************************
namespace EdFi.Dashboards.Core
{
    public enum SchoolMetricEnum
    {
        None = 0,
        Overview = 200,
        OverviewEngagement = 201,
        OverviewAssessment = 203,
        Attendance = 210,
        Discipline = 416,
        AcademicProgress = 202,
        AssessmentMetrics= 203,
        StateAssessmentPerformance=233,
        StateAssessmentELAReading=234,
        StateAssessmentMathematics=235,
        StateAssessmentScience=236,
        StateAssessmentSocialStudies=237,
        StateAssessmentWriting=1053,
        StateAssessmentTestNonParticipation=240,
        StateAssessmentRepeatFailures = 244,
        TPM = 279,
        TPMELAReading = 280,
        TPMMath = 281,
        TPMScience = 282,
        StateAssessmentExitLevel = 239,
        CourseGradeMetrics = 204,
        GrowthMetrics = 205,
        AcademicChallenge=206,
        StateAssessmentCommendedPerformance =1017,
        CollegeAndCareerReadiness=207,
        PSAT = 325,
        SAT = 328, 
        ACT=331,
        SchoolEnvironment = 347,
        QualityWorkforce=209,
        OperationsDashboard = 1029,
        OperationsDashboardStaff = 1030,
        TeacherAttendance = 1031,
        TeacherAttendanceRate = 361,
        TeacherAttendanceRateCurrentPeriod = 1032,
        TeacherAttendanceRateYearToDate = 1034,
        ExperienceEducationCertifications = 1035,
        TeacherExperience = 369,
        TeacherExperienceAll = 370,
        TeacherExperienceELA = 371,
        TeacherExperienceMath = 372,
        TeacherExperienceScience = 424,
        TeacherExperienceSocialStudies = 425,
        TeacherEducation = 1069,
        TeacherEducationBachelors = 1070,
        TeacherEducationMasters = 1071,
        TeacherCertification = 365,
        TeacherCertificationELA = 366,
        TeacherCertificationMath = 367,
        TeacherCertificationScience = 368,
        TeacherCertificationSocialStudies = 426,
        TeacherCertificationGeneralist = 1036,
        RetentionStaffing = 1037,
        RetentionStaffingTeacher = 375,
        DIBELS = 1482,
        LanguageAssessmentProficiency = 1002,
        GradesBelowCLevel = 262,
        CreditAccumulation = 283,
        OnTrackToGraduate = 288,
        AdvancedCoursePotential = 290,
        HighSchoolGraduationPlan = 1470
    }
}