#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.LocalEducationAgency.Views.Overview
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
    using EdFi.Dashboards.Common;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    
    #line 4 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Areas.LocalEducationAgency.Controllers;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Utilities.ExtensionMethods.HtmlHelper;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
    using EdFi.Dashboards.Presentation.Web.Utilities;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
    using EdFi.Dashboards.Resources.Models.LocalEducationAgency.Overview;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
    using EdFi.Dashboards.Resources.Navigation;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/LocalEducationAgency/Views/Overview/Get.cshtml")]
    public class Get : System.Web.Mvc.WebViewPage<OverviewModel>
    {
        public Get()
        {
        }
        public override void Execute()
        {

WriteLiteral("           \n");








WriteLiteral("\n");


            
            #line 11 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
  
    ViewBag.Title = "Local Education Agency Overview";


            
            #line default
            #line hidden
WriteLiteral("\n");


DefineSection("ContentPlaceHolderHead", () => {

WriteLiteral("\n    <title>\r\n        ");


            
            #line 17 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
    Write(Html.Action("Title", typeof(LocalEducationAgencyLayoutController).GetControllerName(), new { subTitle = "Overview" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </title>\n    <script type=\"text/javascript\">\r\n        var pageArea = { Area" +
": \'local education agency\', Page: \'Academic Dashboard - Overview\' };\r\n    </scri" +
"pt>\n");


});

WriteLiteral("\n\n");


DefineSection("ContentPlaceHolder1", () => {

WriteLiteral("\n    <div class=\"l-metrics\">\r\n        <h2 class=\"hidden\">LEA Overview</h2>\r\n     " +
"   <div class=\"accountability-rating\">\r\n");


            
            #line 28 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
             foreach (var rating in Model.AccountabilityRatings) 
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>\r\n                    <span>");


            
            #line 31 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
                     Write(rating.Attribute);

            
            #line default
            #line hidden
WriteLiteral(":</span>\n                    <span>");


            
            #line 32 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
                     Write(rating.Value);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </p>\n");



            #line 34 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n\r\n");

            

            #line 37 "..\..\Areas\LocalEducationAgency\Views\Overview\Get.cshtml"
           Html.RenderAction("Get", "Metrics",
                                              new
                                                  {
                                                      renderingMode = Model.RenderingMode,
                                                      localEducationAgencyId = Model.LocalEducationAgencyId,
                                                      metricVariantId = Model.MetricVariantId
                                                  });
            

            
            #line default
            #line hidden
WriteLiteral("    </div>\n");

            
});

WriteLiteral("\n");


        }
    }
}
#pragma warning restore 1591
