#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Presentation.Core.Areas.Admin.Views.MetricThreshold
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 2 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
    using EdFi.Dashboards.Common;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Metric.Resources.Models;
    using EdFi.Dashboards.Presentation.Architecture.Mvc.Extensions;
    
    #line 4 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Areas.Admin.Controllers;
    
    #line default
    #line hidden
    using EdFi.Dashboards.Presentation.Web.Utilities;
    using EdFi.Dashboards.Resources.Navigation;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/MetricThreshold/Get.cshtml")]
    public class Get : System.Web.Mvc.WebViewPage<IEnumerable<EdFi.Dashboards.Presentation.Core.Areas.Admin.Models.MetricThresholdMetricModel>>
    {
        public Get()
        {
        }
        public override void Execute()
        {





DefineSection("ContentPlaceHolderHead", () => {

WriteLiteral("\r\n    <title>");


            
            #line 6 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
       Write(Html.Action("Title", typeof(AdminLayoutController).GetControllerName(), new { subTitle = "Admin" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </title>\r\n");


});

WriteLiteral("\r\n");


DefineSection("ContentPlaceHolder1", () => {

WriteLiteral("\r\n");


            
            #line 10 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
     using (@Html.BeginForm(new { id = "ThresholdForm" }))
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>METRIC THRESHOLD - Grades and Credits</h2>\r\n");



WriteLiteral("        <div id=\"actionMessage\">\r\n        </div>\r\n");



WriteLiteral(@"        <div class=""l-metrics"">
        <table summary=""Table for setting new metric threshold."">
        <thead>
            <tr id=""vMetric1447"" class=""MetricHeaderTitle"">
                <th class=""HeaderTabGrayBGBig"" title="""" style=""width: 450px; text-align: left;"">
                    <span id=""vMetricVariantId1447"" class=""metricId"">1447-CurrentYear </span><a name=""Course Grades"">
                                                                                                 Course Grades</a> <a name=""m1447""></a>
                </th>
                <th class=""HeaderTabGrayBGBig"" style=""width: 100px; text-align: center;"">
                    <label for=""Threshold"">METRIC THRESHOLD</label>
                </th>
                <th class=""HeaderTabGrayBGBig"">
                </th>
                <th class=""HeaderTabGrayBGBig"">
                </th>
            </tr>
        </thead>
        <tbody>
");


            
            #line 33 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
             foreach (var metricThresholdGetModel in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("            <tr class=\"container\">\r\n                <td class=\"MetricSubTitle\">\r\n" +
"                <h3 id=\"vName");


            
            #line 37 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                         Write(metricThresholdGetModel.MetricThresholdGetResponse.MetricId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"title\">");


            
            #line 37 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                                                                                                      Write(metricThresholdGetModel.MetricTitle);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                <p id=\"vDescription");


            
            #line 38 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                               Write(metricThresholdGetModel.MetricThresholdGetResponse.MetricId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"description\">\r\n                    ");


            
            #line 39 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
               Write(metricThresholdGetModel.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </p>\r\n                </td>\r\n                <td class=\"MetricC" +
"ontentText\" style=\"text-align: center;\">\r\n                    <input data-val=\"t" +
"rue\" data-val-number=\"The field Threshold must be a number.\" id=\"Threshold");


            
            #line 43 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                                                                                                            Write(metricThresholdGetModel.MetricThresholdGetResponse.MetricId);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"Threshold\" style=\"width:30px; text-align:right;\" type=\"text\" value=\"");


            
            #line 43 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                                                                                                                                                                                                                                                     Write(Convert.ToInt32(metricThresholdGetModel.MetricThresholdGetResponse.Threshold / metricThresholdGetModel.Multiplier));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                </td>\r\n                <td class=\"MetricTitle\">\r\n            " +
"        <a onclick=\"put(");


            
            #line 46 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                               Write(metricThresholdGetModel.MetricThresholdGetResponse.MetricId);

            
            #line default
            #line hidden
WriteLiteral(", ");


            
            #line 46 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                                                                                             Write(metricThresholdGetModel.MetricThresholdGetResponse.IsInclusive.ToString().ToLowerInvariant());

            
            #line default
            #line hidden
WriteLiteral(", ");


            
            #line 46 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                                                                                                                                                                                            Write(metricThresholdGetModel.Multiplier);

            
            #line default
            #line hidden
WriteLiteral(")\" href=\"javascript:void(0);\">Save</a>\r\n                </td>\r\n                <t" +
"d class=\"MetricTitle\">\r\n                    <a onclick=\"resetMetric(");


            
            #line 49 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                                       Write(metricThresholdGetModel.MetricThresholdGetResponse.MetricId);

            
            #line default
            #line hidden
WriteLiteral(", ");


            
            #line 49 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                                                                                                     Write(Convert.ToInt32(metricThresholdGetModel.DefaultValue / metricThresholdGetModel.Multiplier));

            
            #line default
            #line hidden
WriteLiteral(")\" href=\"javascript:void(0);\">Reset to default : ");


            
            #line 49 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                                                                                                                                                                                                                                                 Write(Convert.ToInt32(metricThresholdGetModel.DefaultValue / metricThresholdGetModel.Multiplier));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </td>\r\n            </tr>\r\n");


            
            #line 52 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n        </table>\r\n        </div>\r\n");


            
            #line 56 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <script language=\"javascript\">\r\n\r\n        $(document).ready(function () {\r\n  " +
"          $(\'#actionMessage\').hide();\r\n\r\n        });\r\n\r\n        var successColor" +
" = \'#DBFFDC\';\r\n        var errorColor = \'#FFA3A7\';\r\n\r\n        function writeMess" +
"age(message, messageType) {\r\n\r\n            var highlightColor = \'#FFFFFF\';\r\n\r\n  " +
"          if (messageType == \'success\') {\r\n                highlightColor = succ" +
"essColor;\r\n            }\r\n            if (messageType == \'error\') {\r\n           " +
"     highlightColor = errorColor;\r\n            }\r\n\r\n            $(\'#actionMessag" +
"e\').html(message);\r\n            $(\'#actionMessage\').animateHighlight(highlightCo" +
"lor, 6000);\r\n            $(\'#actionMessage\').show();\r\n            setTimeout(fun" +
"ction () {\r\n                if ($(\'#actionMessage\').length > 0) {\r\n             " +
"       $(\'#actionMessage\').hide(\'slow\');\r\n                }\r\n            }, 6000" +
");\r\n        }\r\n\r\n        function IsValidThreshold(metricId) {\r\n            var " +
"re = /^([1-9]|[1-9]\\d|100)$/;\r\n            var thresholdInput = $(\'#Threshold\' +" +
" metricId).val();\r\n            if (re.test(thresholdInput)) {\r\n                r" +
"eturn true;\r\n            }\r\n            return false;\r\n        }\r\n\r\n        func" +
"tion put(metricId, isInclusive, multiplier) {\r\n\r\n            if (!IsValidThresho" +
"ld(metricId)) {\r\n                $(\'#Threshold\' + metricId).focus();\r\n          " +
"      $(\'#Threshold\' + metricId).select();\r\n                alert(\'Invalid value" +
" entered.\');\r\n                return false;\r\n            }\r\n\r\n            var th" +
"reshold = $(\'#Threshold\' + metricId).val();\r\n            var postObj = {\r\n      " +
"          MetricId: metricId,\r\n                Threshold: threshold * multiplier" +
",\r\n                IsInclusive: isInclusive\r\n            };\r\n\r\n            $.aja" +
"x({\r\n                url: \' ");


            
            #line 114 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                  Write(Url.Action("Get", "MetricThreshold", null, "https"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                type: 'POST',
                data: JSON.stringify(postObj),
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    writeMessage('Save successful - The change will display after the next build.', 'success');
                },
                error: function () {
                    writeMessage('Error occured saving value', 'error');
                }
            });
        }

        function resetMetric(metricId, defaultValue) {

            var postObj = { MetricId: metricId };

            $.ajax({
                url: ' ");


            
            #line 132 "..\..\Areas\Admin\Views\MetricThreshold\Get.cshtml"
                  Write(Url.Action("Delete", "MetricThreshold", null, "https"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                type: 'POST',
                data: JSON.stringify(postObj),
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    $('#Threshold' + metricId).val(defaultValue);
                    writeMessage('Reset to default successful - The change will display after the next build.', 'success');
                },
                error: function () {
                    writeMessage('Error occured resetting to default value', 'error');
                }
            });
        }

        $.fn.animateHighlight = function (highlightColor, duration) {
            var highlightBg = highlightColor || ""#FFFF9C"";
            var animateMs = duration || 1500;
            var originalBg = this.css(""backgroundColor"");
            this.stop().css(""background-color"", highlightBg).animate({ backgroundColor: originalBg }, animateMs);
        };

    </script>
");


});

WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
